### ISSUE TITLE
Missing CommonModule import in Ng2Bs3ModalModule.

### ISSUE THREAD

**Issue by jcannata** [dougludlow/ng2-bs3-modal#100]
With the new modules feature, you must import modules whose public classes you need to reference in your module's component templates.

The ModalComponent relies on ngClass in its template so you must import CommonModule otherwise you will get a Template parser error when trying to use a dialog.

So in ng2-bs3-modal.ts you must add it like so...

`...
import { CommonModule } from '@angular/common';
...`

`@NgModule({`
`    imports: [CommonModule],`
`    declarations: MODAL_DIRECTIVES,`
`    exports: MODAL_DIRECTIVES`
`})`
`export class Ng2Bs3ModalModule { }`

**Comment by dougludlow** [comment]
Fixed with #101.
