### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by RodEsV** [dougludlow/ng2-bs3-modal#102]
I was trying to do the demo for my own but when I copy the simplest example I get

Unhandled Promise rejection: Template parse errors:
Can't bind to 'show-close' since it isn't a known property of 'modal-header'.

I don't understand what is wrong!

**Comment by dougludlow** [comment]
What did you end up with?

**Comment by RodEsV** [comment]
It was a matter of imports, now everything works. 
Thanks

**Comment by dougludlow** [comment]
👍
