### ISSUE TITLE
Demo imports Ng2Bs3ModalModule from '../src/ng2-bs3-modal/ng2-bs3-modal';

### ISSUE THREAD

**Issue by lcurrens** [dougludlow/ng2-bs3-modal#103]
I am having trouble getting ng2-bs3-modal working with SystemJS, importing Ng2Bs3ModalModule from the NPM install with version 0.8.1.  I am trying to do an RC6 port, using the new Ng2Bs3ModalModule.  
I can't seem to get the correct systemjs.config.js configuration to allow it to properly import the Ng2Bs3ModalModule.

The Demo is importing from src, we are not able to do from the NPM install.
import { Ng2Bs3ModalModule } from '../src/ng2-bs3-modal/ng2-bs3-modal';

Can you update the demo to use the NPM install and have the correct Systemjs.config.js and import statement for the Ng2Bs3ModalModule?

**Comment by lcurrens** [comment]
Nevermind, got it working.

**Comment by dougludlow** [comment]
Sweet!
