### ISSUE TITLE
AoT compiler : Unexpected value 'Ng2Bs3ModalModule' imported by the module 'SharedModule'

### ISSUE THREAD

**Issue by belapie** [dougludlow/ng2-bs3-modal#105]
When i'm trying to compile AoT with ngc i get this error :

`Unexpected value 'Ng2Bs3ModalModule' imported by the module 'SharedModule'`

SharedModule.ts :

```
import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TranslateModule } from 'ng2-translate';
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
import { RemoveHost } from './directives/remove_host.directive';
import { AuthGuard } from './guards/auth.guard';
import { GuestGuard } from './guards/guest.guard';
import { AuthService } from './services/auth.service';

@NgModule({
    imports: [CommonModule, Ng2Bs3ModalModule],
    declarations: [RemoveHost],
    exports: [
        TranslateModule,
        CommonModule,
        FormsModule,
        RemoveHost,
        Ng2Bs3ModalModule
    ]
})
export class SharedModule {

    static forRoot(): ModuleWithProviders {
        return {
            ngModule: SharedModule,
            providers: [AuthGuard, AuthService, GuestGuard]
        };
    }
}
```

TypeScript 2.0.2
Angular : 2.0.0-rc7 (not working either with rc6)

**Comment by koleary94** [comment]
Hey @belapie . After running into a similar problem it appears that the issue is the lack of a `metadata.json` file in this project. See [this official angular thread](https://github.com/angular/angular/issues/11262) for reference

**Comment by dougludlow** [comment]
@belapie, @koleary94 - I just releases v0.9.2, is this issue still present there?

**Comment by belapie** [comment]
@dougludlow the issue is still present..

`Error: Unexpected value 'Ng2Bs3ModalModule' imported by the module 'SharedModule'`

**Comment by galvanu** [comment]
+1

Facing the same issue in my project. I work with angular 2.0.0 and use v0.9.2 which also with angular 2
@belapie , @koleary94  - do you have any solution for this?

**Comment by dougludlow** [comment]
@belapie, @koleary94, @galvanu - try with v0.10.3. I believe I've got it working. I just needed to compile `ng2-bs3-modal` with the [@angular/compiler-cli](https://github.com/angular/angular/tree/master/modules/@angular/compiler-cli) (`ngc`).

**Comment by galvanu** [comment]
@dougludlow - I updated the version and it looks like it pass this step, the problem is I have other problems in my project which fails the AoT so the build fails.
But again these are all unrelated errors to the ng2-bs3-modal so I guess building it with ngc solves this issue.
I think it is a good time for v1.0.0 ;)

**Comment by dougludlow** [comment]
@belapie, @koleary94 - any feedback?

**Comment by belapie** [comment]
@dougludlow now it's working with 0.10.4!

Thanks

**Comment by felipelvira** [comment]
Hi @dougludlow , I'm still facing this issue.
ng2-bs3-modal -v : 0.10.4
angular-cli : 1.0.0-beta.18

**Comment by Rambuto** [comment]
Hello, do you have any progress about AoT ?
