### ISSUE TITLE
Problem after migration to stable version

### ISSUE THREAD

**Issue by Rambuto** [dougludlow/ng2-bs3-modal#109]
Hello, after migration to stable version i have problem with running project
Have next error:
```
ERROR in /home/admin/Documents/work/migration/geolitik_v2_web/node_modules/ng2-bs3-modal/ng2-bs3-modal.d.ts
(7,40): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
```
Can you help me please ?

**Comment by jcannata** [comment]
Are you compiling with TypeScript 2.0 or higher?

**Comment by Rambuto** [comment]
"typescript": "1.8.7"

**Comment by dougludlow** [comment]
@Rambuto - upgrade to v0.9.2. You shouldn't see these errors.
