### ISSUE TITLE
ng2 2.0 yet? + demos not working...

### ISSUE THREAD

**Issue by born2net** [dougludlow/ng2-bs3-modal#110]
ng2 2.0 yet? + demos not working...

Regards,

Sean

**Comment by kinkoazc** [comment]
+1 Please merge the 2.0 PR.

**Comment by dougludlow** [comment]
@born2net, @kinkoazc - v0.9.2 should be what you're looking for.

**Comment by born2net** [comment]
tx!!

**Comment by kinkoazc** [comment]
Thank you!
