### ISSUE TITLE
Import jQuery if not available globally

### ISSUE THREAD

**Issue by renehamburger** [dougludlow/ng2-bs3-modal#111]
You should probably allow for jQuery being loaded as a module rather than being available locally in your  [modal-instance](https://github.com/dougludlow/ng2-bs3-modal/blob/master/src/ng2-bs3-modal/components/modal-instance.ts#L6), e.g. `const $ = window['jQuery'] || require('jquery')`. That is going to happen increasingly.

For anyone else encountering this, Webpack's imports loader can be used as a temporary workaround:
`
  loaders: {
    test: /\/ng2-bs3-modal\//,
    loader: 'imports?jQuery=jquery'
  }
`

**Comment by dougludlow** [comment]
@renehamburger I'll need to look into that.

**Comment by dougludlow** [comment]
Another way to make jQuery available globally in webpack is through the ProvidePlugin:

```
plugins: [
    new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery'
    })
]
```

**Comment by dougludlow** [comment]
@renehamburger - `const $ = window['jQuery'] || require('jquery')` works fine with commonjs but not systemjs. I would need a solution that works for both.

**Comment by dougludlow** [comment]
@renehamburger not only that, but bootstrap requires that it is global also. This is a limitation with bootstrap.

**Comment by renehamburger** [comment]
Yes, true. I've added another imports loader section to provide jQuery for all bootstrap files:
```
loaders: [{
  test: /\/bootstrap\/js\//,
    loader: 'imports?jQuery=jquery'
}]
```
In other words: this issue needs to be resolved through the Webpack config file for now. Thanks for looking into this!
