### ISSUE TITLE
close is no working!

### ISSUE THREAD

**Issue by RodEsV** [dougludlow/ng2-bs3-modal#112]
Once I have display the modal, I'm not able to close it.
It says error context this.modal is undefined!

Inside my component I'm using a reference to my modal View child, because I have to close the modal if some variable is true. I'm able to do it inside the .html file but no from the .ts file

Any suggestions ?

**Comment by wartab** [comment]
Sounds like you're misusing this. Can you please show some code?

**Comment by RodEsV** [comment]
I was writing this and I notice that I have two `@ViewChilds`  with different names.
And that was generating the problem :s
![selection_003](https://cloud.githubusercontent.com/assets/4596532/18816243/f0ed04ac-830a-11e6-8983-7f615d65a9bf.png)

**Comment by dougludlow** [comment]
@RodEsV you need to move the `@ViewChild('modalError')` to just above the `modalError` property.

**Comment by dougludlow** [comment]
@RodEsV were you able to get this solved?

**Comment by RodEsV** [comment]
Yes, thank you. Finally I decided to remove that part

**Comment by dougludlow** [comment]
FYI, I added another [example](https://github.com/dougludlow/ng2-bs3-modal#multiple-modals-in-a-component) to the readme that shows how to use mulitple modals within a component.
