### ISSUE TITLE
modal.d.ts typescript syntax error

### ISSUE THREAD

**Issue by galvanu** [dougludlow/ng2-bs3-modal#113]
Hi, I'm using version 0.9.2 and getting a lot of typescript error during build in the file components/modal.d.ts

/node_modules/ng2-bs3-modal/components/modal.d.ts(16,14): error TS1005: '=' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(16,23): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(17,14): error TS1005: '=' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(17,30): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(18,14): error TS1005: '=' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(18,30): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(18,32): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(19,24): error TS1005: ',' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(20,18): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(20,32): error TS1005: '(' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(21,26): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(22,15): error TS1109: Expression expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(22,24): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(22,39): error TS1005: '(' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(23,17): error TS1109: Expression expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(23,23): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(23,38): error TS1005: '(' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(24,14): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(24,29): error TS1005: '(' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(25,20): error TS1005: ';' expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(26,5): error TS1128: Declaration or statement expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(27,5): error TS1128: Declaration or statement expected.
/node_modules/ng2-bs3-modal/components/modal.d.ts(28,1): error TS1128: Declaration or statement expected.`

I wonder if this is a local issue or it should be fixed in the d.ts file?

**Comment by dougludlow** [comment]
@galvanu - what version of typescript are you using?

**Comment by dougludlow** [comment]
I compile with typescript v2 which emits readonly definitions on properties. If you're compiling with 1.8, you'll see these errors.

**Comment by priesett** [comment]
I'm seeing the same thing, typescript 2.0.3 here. Started with the 0.9.7 version.

**Comment by dougludlow** [comment]
@priesett - oh phew... i thought i was going crazy there for a moment. 😄

**Comment by priesett** [comment]
@galvanu In my case, I needed to npm install -g typescript as my global typescript was still in v1

**Comment by galvanu** [comment]
It was my issues as well, theank!

**Comment by mptorrejon** [comment]
I was using gulp to compile my ts files. I also had to update the typescript dependency in gulp-typescript package.json and it worked fine.

**Comment by DiasAmanda** [comment]
I am using VS2015, when I run tsc -v   I have TypeScript version 2.0.9
When I go to 'Help / About Microsoft Visual Studio', I have TypeScript version 2.0.6
I tried to unload the project and edit the project, setting the <TypeScriptToolsVersion> to 2.0, instead of 1.8 as it was, but I only get more errors...
So I returned this var to 1.8, and just have errors with this file 'modal.d.ts', the same error of @galvanu .

I already tried to set my user environment variables, 'PATH', but nothing worked. 

=/
