### ISSUE TITLE
ModalComponent angular final version 2.0 open don't exist

### ISSUE THREAD

**Issue by loliparra80** [dougludlow/ng2-bs3-modal#114]
I'm working with ngModule already, but when I try to use the instance of ModalComponent inside my typescript component with viewchild:
   @ViewChild('modalEpisode') modalEpisode:ModalComponent; 

when I try to use the methods for ModalComponent, like open, don't recognize the method:
this.modalEpisode.open();

 Error: 
![image](https://cloud.githubusercontent.com/assets/19977368/18913695/7e5bf37c-8589-11e6-960b-15d32e831ed8.png)

what can I do? because I need to open in the typescript. Thanks

**Comment by dougludlow** [comment]
@loliparra80 - what does your html template look like?

**Comment by belapie** [comment]
@loliparra80 maybe it's because the modal.d.ts contains the new TS2.0 "readonly" and your IDE doesn't support it.

```
readonly fadeClass: boolean;
readonly dataKeyboardAttr: boolean;
readonly dataBackdropAttr: string | boolean;
```

**Comment by loliparra80** [comment]
I'm using visual stuido code Insiders, until now all the libraries work fine.
HTML:

<modal [animation]="animation" [backdrop]="backdrop" size='lg' #modalPatient>
        content  
</modal>

When I compile the code appear error from modal.d.ts:
node_modules/ng2-bs3-modal/components/modal.d.ts(23,38): error TS1005: '(' expected.                                       
node_modules/ng2-bs3-modal/components/modal.d.ts(24,14): error TS1005: ';' expected.                                       
node_modules/ng2-bs3-modal/components/modal.d.ts(24,29): error TS1005: '(' expected.                                       
node_modules/ng2-bs3-modal/components/modal.d.ts(25,20): error TS1005: ';' expected.                                       
node_modules/ng2-bs3-modal/components/modal.d.ts(26,5): error TS1128: Declaration or statement expected.                   
node_modules/ng2-bs3-modal/components/modal.d.ts(27,5): error TS1128: Declaration or statement expected.                   
node_modules/ng2-bs3-modal/components/modal.d.ts(28,1): error TS1128: Declaration or statement expected.

**Comment by dougludlow** [comment]
@loliparra80 - I believe vscode insiders is [still using 1.8](https://github.com/Microsoft/vscode/issues/9637). You can tell it to use your current project's version by updating the `typescript.tsdk` property of your vscode project settings file to point to the typescript instance installed in `node_modules`. See [Using Newer TypeScript Versions](https://code.visualstudio.com/docs/languages/typescript#_using-newer-typescript-versions).
