### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by diegounanue** [dougludlow/ng2-bs3-modal#115]
I'm using webpack, I Install version "ng2-bs3-modal": "^0.10.3"
And in Chrome when I start the app says:

"Uncaught ReferenceError: System is not defined"

When I click on the error link it goes to this line:

System.register("ng2-bs3-modal/components/modal-instance", ['rxjs/Observable', 'rxjs/add/operator/map', 'rxjs/add/observable/fromEvent'], function(exports_1, context_1) {

**Comment by dougludlow** [comment]
@diegounanue - take a look at your `tsconfig.json` and make sure that the `module` property is set to `commonjs`. See http://stackoverflow.com/questions/35075130/why-webpack-bundled-as-system-register.

FYI, i've just put up a [webpack](https://github.com/dougludlow/ng2-bs3-modal-demo-webpack) demo that might be worth checking out.

**Comment by diegounanue** [comment]
Yes, I have that configuration on my project:

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": false
  }
}
Still having the same issue. The modal works, but the browser displays "ng2-bs3-modal.js:19Uncaught ReferenceError: System is not defined"

**Comment by dougludlow** [comment]
Hmm... it sounds like you're somehow including the systemjs bundle instead of the commonjs files. How are you importing/resolving ng2-bs3-modal in your project?

**Comment by diegounanue** [comment]
Yes, it was my bad, I thought I have to include it like in a require ('ng2-bs3-modal/bundles/ng2-bs3-modal.js'); on a vendor.ts for webpack but that's no necessary. I just import it in the app.module.ts and it works. Thanks for the quick response! By the way very good job!
