### ISSUE TITLE
this.$modal.modal is not a function in 2.1.0-beta.0

### ISSUE THREAD

**Issue by jairusm** [dougludlow/ng2-bs3-modal#116]
Hi, im having issue in 2.1.0-beta.0 everytime i click to open the modal. Isn't the compatibility issue?
I currently using the ng2-bs3-modal 0.10.4 version.
![image](https://cloud.githubusercontent.com/assets/19209238/19050989/9660818c-89e3-11e6-8448-6dcd8c03eaea.png)

**Comment by dougludlow** [comment]
@jairusm - this error indicates that bootstrap.js hasn't been loaded. How are you including the bootstrap.js in your project?

**Comment by jairusm** [comment]
Im including it in index.html. I included first the bootstrap.js then the modal after the System.import('app')

**Comment by dougludlow** [comment]
@jairusm - hmm... could you provide some more code so I can get a better idea of what's going on?

**Comment by dougludlow** [comment]
@jairusm - you're index.html perhaps and your systemjs config?

**Comment by jairusm** [comment]
This is my index.html, but i dont have any mapping for the model in system.config 
![image](https://cloud.githubusercontent.com/assets/19209238/19052202/7b4d09ce-89e8-11e6-83be-520bfe92e99f.png)

**Comment by jairusm** [comment]
Btw, im using webpack :)

**Comment by dougludlow** [comment]
@jairusm typically when you use webpack, it bundles all of the files into a single file and you include script tags in your index.html for just that. How are you using webpack in your case?

**Comment by dougludlow** [comment]
@jairusm any updates here?

**Comment by jmny** [comment]
i think I have the same problem, i use angular 2.0.1 and     "ng2-bs3-modal": "^0.10.4"

![capture d ecran de 2016-10-11 18-25-55](https://cloud.githubusercontent.com/assets/216424/19279129/58400b90-8fe0-11e6-9ca1-e72b6ec1d6b0.png)

my code 

`
@Component({
      selector: 'zones',
      template: `
      <div class="container-fluid">
//...  
<modal #product >
      <modal-header [show-close]="true">
          <h4 class="modal-title"><span *ngIf="current">{{current.name}}</span></h4>
      </modal-header>
      <modal-body>
          Hello World!
      </modal-body>
      <modal-footer [show-default-buttons]="true"></modal-footer>
  </modal>        
//... in for loop on p 
            <td (click)="openPopin(p)">
                 <button class="btn btn-sm ">Modifier</button>
            </td>
// ...
       </div>
      `
  })


export class ZonesComponent {
      @ViewChild('product') modal:ModalComponent;

//...
     public openPopin(p:Product) {
          this.current = p;
          console.log(this.modal);
          this.modal.open();  
      }
}
`

**Comment by dougludlow** [comment]
@jmny how are you loading `bootrap.js`?

**Comment by jmny** [comment]
the mistake was here, bootstrap.js wasn't loaded. thank you :)

**Comment by guzmo** [comment]
Have the same error, when removing this from my webpack, just for testing different things :P
```
plugins: [
    new webpack.ProvidePlugin({
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery'
    })
  ]
```

I get 
`Uncaught Error: Bootstrap's JavaScript requires jQuery`

So I guess both jquery and bootstrap is loaded but still that error hmm

**Comment by talha-khan-10p** [comment]
Having same error. 
Importing jquery and bootstrap in vendors.ts didn't work because bootstrap.js needs jquery(initialized jquery).

This solves my issue:
https://github.com/AngularClass/angular2-webpack-starter/wiki/How-to-use-Bootstrap-4-and-Sass-(and-jQuery)

Basically, the solution is to load bootstrap through some loader that ensures that jquery is properly imported.

**Comment by matthewhegarty** [comment]
I had the same issue when using angular-cli (`1.0.0-beta.19-3`).  The solution was to ensure that bootstrap.js was present in the scripts declaration in angular-cli.json:

```
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"
      ],
```

**Comment by jairusm** [comment]
Sorry for the very late reply and for the misunderstanding regarding webpack as i have two projects.. I was able to make it working by adding this "import 'bootstrap'" to the component where im using the modal :)

**Comment by Ankita-Jaiswal** [comment]
Install jquery and bootstrap in your project

npm install jquery
npm install bootstrap

then import both in the file (for eg model-view.component.ts) where you are using this modal
import 'jquery';
import 'bootstrap';

For me this worked flawlessly :)
