### ISSUE TITLE
ng2-bs4-modal - SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by famecrave** [dougludlow/ng2-bs3-modal#117]
Hi
Am using ng2-bs4-modal with angular 2.0.2 and bootstrap4

I did the setup as advised in https://www.npmjs.com/package/ng2-bs4-modal but am getting below error in browser. Plz can you advise.

```
localhost/:41 Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:8080/app/app.module.js:14:23)
	    at eval (http://localhost:8080/app/app.module.js:64:4)
	    at eval (http://localhost:8080/app/app.module.js:65:3)
	Evaluating http://localhost:8080/node_modules/ng2-bs4-modal/ng2-bs4-modal
	Evaluating http://localhost:8080/app/app.module.js
	Evaluating http://localhost:8080/app/main.js
	Error loading http://localhost:8080/app/main.js(anonymous function) @ localhost/:41
```

**Comment by dougludlow** [comment]
@famecrave, I'm guessing you're getting a 404 on http://localhost:8080/node_modules/ng2-bs4-modal/ng2-bs4-modal (notice there's no extension) and your web server is returning html and hence the "Unspected token <."

**Comment by dougludlow** [comment]
@famecrave have you had any luck figuring out what's going on here?

**Comment by dougludlow** [comment]
Closing for now. Feel free to open if you're still experiencing issues.
