### ISSUE TITLE
Modal closes on page update

### ISSUE THREAD

**Issue by dustin486** [dougludlow/ng2-bs3-modal#118]
The modals work fine on a project that I am working on, but if you have a modal open and the page updates (it has content from Firebase that constantly changes) then the modal will close out. Note the page does not do a full refresh, just the data from Firebase updates. I looked through the open/closed issues and did not notice anything pertaining to this. This project is running Angular 2.0 with the AngularFire module. Any ideas?

**Comment by dougludlow** [comment]
@dustin486 - interesting. I haven't tested that scenario exactly. Could you provide some more details on how you're using the modal? Code snippets or demo project?

**Comment by dustin486** [comment]
I do not have the code in front of me right now, but I got to thinking about it later last night. All of the data from firebase is presented on the page inside of div's with the angular for loop. I was creating a separate modal inside each div so that it could (easily) have the data for that specific one. Once you clicked inside of that div, it would open the modal. As soon as any div on the page was updated with new data from Firebase, it would close out the modal. I was thinking this may be because I was creating them inside the for loop and it was re-drawing everything each time the data was updated. Can't confirm this, was just a thought I had.

If its ok with you I can shoot you an email later with the project so you can check it out.

**Comment by dougludlow** [comment]
@dustin486 sure, that would be great. 

Yeah, that makes sense. When the firebase call comes back you may want to merge it into the existing array instead of replacing it as that will cause it to "redraw" everything. There's probably other ways to approach that as well, I'll do some research and see what I come up with.

**Comment by dougludlow** [comment]
@dustin486 - might be as simple as specifying `trackBy` in the `ngFor`: 

> It is possible for the identities of elements in the iterator to change while the data does not. This can happen, for example, if the iterator produced from an RPC to the server, and that RPC is re-run. Even if the data hasn't changed, the second response will produce objects with different identities, and Angular will tear down the entire DOM and rebuild it (as if all old elements were deleted and all new elements inserted). This is an expensive operation and should be avoided if possible.
>
>To customize the default tracking algorithm, NgFor supports trackBy option. trackBy takes a function which has two arguments: index and item. If trackBy is given, Angular tracks changes by the return value of the function.

See [NgFor](https://angular.io/docs/ts/latest/api/common/index/NgFor-directive.html#!#ngForTrackBy-anchor).

**Comment by dustin486** [comment]
@dougludlow was correct, trackBy is exactly what was needed in this situation. Just added it to the for loop statement. Simple fix. Thanks again!
