### ISSUE TITLE
Problems implementing custom-sized modal

### ISSUE THREAD

**Issue by jpat82792** [dougludlow/ng2-bs3-modal#121]
I've been able to implement the Modal component successfully in one of my own components. I am able to resize it using modal-lg and modal-sm respectively. However, I would really like to have a custom sized modal. Below is the current attempt at making it resize. I just included portions I thought would be relevant to the discussion.

From component.ts:
`    cssClass: string = 'modal-lg';`
From component.html:
`<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()" (onDismiss)="dismissed()" [cssClass]="cssClass" #modal  >`
From component.css:
`.modal-lg{
width:1100px;
}`

So nothing happens when I do this. Any thoughts on where the problem lies?

Also thanks for this library, it is really great!

**Comment by dougludlow** [comment]
@jpat82792: The way that you're using it is correct. It might just be that you need to use a different class name because it clashes with the bootstrap `.modal-lg` class.

**Comment by jpat82792** [comment]
So I updated the component.ts:
`cssClass: string = 'expand-modal'`

The css:
`.expand-modal{
width:1100px;
}`

Still no change.

**Comment by dougludlow** [comment]
@jpat82792: hmm... I don't understand. That should work. Let me put together a demo project tonight and see what I come up with.

**Comment by dougludlow** [comment]
@jpat82792 when you inspect your modal in the broswer, is the `.expand-modal` not being applied to it?

**Comment by jpat82792** [comment]
It appears to be. I posted what the modal tag contains below.

`<modal _ngcontent-tmp-4="" class="modal in" role="dialog" tabindex="-1" ng-reflect-animation="false" ng-reflect-backdrop="true" ng-reflect-keyboard="true" ng-reflect-css-class="expand-modal" data-keyboard="true" data-backdrop="true" style="display: inline;">
        <div class="modal-dialog expand-modal" ng-reflect-klass="modal-dialog" ng-reflect-ng-class="expand-modal">`

**Comment by dougludlow** [comment]
hmm... is the component.css getting pulled in?

**Comment by jpat82792** [comment]
Yes, I have a bootstrap grid system in <modal-body> that is working as expected

**Comment by dougludlow** [comment]
but the actually `component.css` file? are other classes in there working?

**Comment by jpat82792** [comment]
Sorry I misunderstood. Yes, I have some custom styles working on the page, and have also changed font colors on the modal itself.

**Comment by jpat82792** [comment]
I will make a new component and try out the resize class. I will let you know if that one works. I probably messed something up within one of the files. I have to take care of some errand (should take about 4hrs) and then I will come home and create an minimum viable example. Don't waste your valuable time till I can determine if this is a real problem. I really appreciate your help!

**Comment by dougludlow** [comment]
@jpat82792 sounds good, thanks!

It's weird that the class is on the element, yet the styles aren't being applied.

**Comment by jpat82792** [comment]
Well, I did not have any luck with the MVE. I was unable to resize it after creating brand new stripped down files. I would really appreciate if you could run it in your environment and see if the same happens to you. If it doesn't, I probably have something weird going on with my dev environment. Thanks for your help!

modal-test.component.ts
```
import {Component, ViewChild} from '@angular/core';
import {ModalComponent} from 'ng2-bs3-modal/ng2-bs3-modal';

@Component({
  selector: 'modal-test',
  templateUrl: 'app/modal-test.component.html',
  styleUrls:['app/modal-test.component.css']
})

export class ModalTestComponent{
  /*Modal Logic here*/
    @ViewChild('modal')
    modal: ModalComponent;
    selected: string;
    output: string;

    index: number = 0;
    backdropOptions = [true, false, 'static'];
    cssClass: string = 'modal-test';

    animation: boolean = false;
    keyboard: boolean = true;
    backdrop: string | boolean = true;
    css: boolean = false; //i tried both true and false here...

    closed() {
        this.output = '(closed) ' + this.selected;
        console.log("closed");
    }

    dismissed() {
        this.output = '(dismissed)';
        console.log("dismissed");
    }

    opened() {
        this.output = '(opened)';
        console.log("opened")
    }
    open() {
        this.modal.open();
        console.log("open")
    }
}
```
modal-test.component.html
```
<button (click)="open()">Open Modal</button>
<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()" (onDismiss)="dismissed()" [cssClass]="cssClass" #modal  >
  <modal-header>Header</modal-header>
  <modal-body> 
    <div class="row">
      <div class="col-lg-9"><a>Image should go here</a></div>
      <div class="col-lg-3">Descriptions</div>
    </div>
  </modal-body> <!--[show-default-button]="true" -->
  <modal-footer >
    <button class="btn btn-default" (click)="dismissed()" data-dismiss="modal">Dismiss</button>
  </modal-footer>
</modal>
```
modal-test.component.css
```
.modal-test{
width:1100px;
}
button{
color:red;
}
```

**Comment by dougludlow** [comment]
@jpat82792 I figured out what's going on here. When you include styles in a component, it emulates shadow dom and scopes the css styles to the component's element. However, this doesn't work for the `ng2-bs3-modal` because it is attached to the body. To get around this you have to:

>...use the "`/deep/` selector to force a style down through the child component tree into all the child component views.

See [Component Styles](https://angular.io/docs/ts/latest/guide/component-styles.html#!#-deep-) for more details.

For example, instead of this:

``` css
.modal-test  {
    width: 1100px;
}
```

Do this:

``` css
/deep/ .modal-test  {
    width: 1100px;
}
```

**Comment by jpat82792** [comment]
Thank you for your help! I really appreciate it!

**Comment by dougludlow** [comment]
You're welcome!

**Comment by ashkrit** [comment]
I wasted half of the day and then got to this page. Thanks for it.
