### ISSUE TITLE
modal-header is not a known element

### ISSUE THREAD

**Issue by basherr** [dougludlow/ng2-bs3-modal#124]
I've just copied the below example and pasted into my html component but I get error saying `modal-header` is not known element

```
<button type="button" class="btn btn-default" (click)="projectModal.open()">Open me!</button>
<modal #projectModal>
    <modal-header>
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    <modal-body>
        Hello World!
    </modal-body>
    <modal-footer>
        <button type="button" class="btn btn-default" data-dismiss="modal" (click)="modal.dismiss()">Cancel</button>
        <button type="button" class="btn btn-primary" (click)="modal.close()">Ok</button>
    </modal-footer>
</modal>
//ProjectComponent
import { Component, OnInit, OnDestroy, Inject, ViewChild  } from '@angular/core';
import { NgForm } from "@angular/forms";
import { List } from 'immutable';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
export class ProjectComponent implements OnInit, OnDestroy {
   
  @ViewChild('projectModal')
    projectModal: ModalComponent;
}
```

**Comment by dougludlow** [comment]
@basherr what ended up being the problem?

**Comment by basherr** [comment]
I have imported `Popmodule` into `appModule` and while using it in a seprate `Modul`. I ended up by using it in the same `Module` which worked.

**Comment by VolosUra** [comment]
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';

**Comment by md-ekram** [comment]
i have same problem

![image](https://user-images.githubusercontent.com/31817033/30251640-7e3b4294-9618-11e7-9101-a5b201800b40.png)

**Comment by mafia99** [comment]
Had the same issue. what I did was, I  imported 
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
in app.module.ts
then added it in @NgModule imports list

**Comment by santoshclicks** [comment]
Thanks @mafia99  this did the trick

**Comment by shehzadzafarch** [comment]
> Had the same issue. what I did was, I imported
> import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
> in app.module.ts
> then added it in @NgModule imports list

it worked for me
