### ISSUE TITLE
npm install fails with bootstrap 4 and angular 2 latest version

### ISSUE THREAD

**Issue by tabareh** [dougludlow/ng2-bs3-modal#125]
here are the error messages from npm:
+-- UNMET PEER DEPENDENCY @angular/common@^2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@^2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@^2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@^2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@^2.0.0
+-- UNMET PEER DEPENDENCY bootstrap@~3.3.x
`-- ng2-bs4-modal@0.1.2

**Comment by dougludlow** [comment]
@tabareh what does your package.json look like?

**Comment by dougludlow** [comment]
@tabareh, btw, `ng2-bs3-modal` only supports bootstrap 3.

**Comment by tabareh** [comment]
yeah, I have boostrap 4 and the modals look pretty similar. why not supporting it? you have my package.json attached

[package.zip](https://github.com/dougludlow/ng2-bs3-modal/files/555089/package.zip)
