### ISSUE TITLE
Using ng2-bs3-modal with Angular2-cli 2.1.0

### ISSUE THREAD

**Issue by estradamarkie** [dougludlow/ng2-bs3-modal#127]
I've managed to import the project okay however I'm getting a console.log error of `SyntaxError: Unexpected token <` I've also imported Bootstrap 3.3.7 but still getting the same error even for Bootstrap.

I don't get any network error regarding 404 of the modal, so it is being loaded correctly.

Any idea about this?

**Comment by rajshrimohanks** [comment]
Having the same issue here.

**Comment by zevisert** [comment]
Likely your server is returning your index html. You've probably configured your app to handle deep links by returning index.html when you don't hit anything else. The `Unexpected token <` is probably from the top level `<html>` tag in your index. Verify the response is correct - then reconfigure your loader to provide ng2-bs3-modal.js when requested.

**Comment by dougludlow** [comment]
@estradamarkie @rajshrimohanks you can also take a look at the [angular cli demo](https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli).
