### ISSUE TITLE
modal properties not working

### ISSUE THREAD

**Issue by basherr** [dougludlow/ng2-bs3-modal#128]
When clicked outside of the modal, it get's hidden while `backdrop` property is set to `static`. Also
`keyboard` set to `false` does not work as well.

System: Windows 8
Browser: Chrome latest
```
<section>
    <modal class="modal-center" #accountPayableEditModal [keyboard]="false" [backdrop]="'static'">
            <modal-header>
                <button type="button" class="close"
                    [routerLink]="['/account-payables']"
                    [queryParams]="{pid:pid}">&times;</button>
                <h4 class="modal-title">Update Payroll</h4>
            </modal-header>
            <modal-body>
              test 
            <modal-body>
       </modal>
</section>
```

**Comment by dougludlow** [comment]
Wow, totally skipped this issue. Sorry for never responding. I haven't been able to replicate this.

**Comment by cyrilzaharchenko** [comment]
I also experiencing issue.

**Comment by dougludlow** [comment]
Are you experiencing any particular errors?

**Comment by basherr** [comment]
The issue seems to be fixed with latest version. I can't replicate as well.

**Comment by iamthechad** [comment]
I'm seeing this too with 0.10.4. I was able to replicate on Chrome and Firefox (both on Mac).

**Comment by Dushyant7** [comment]
For me modal properties are not working when modal opens in  ngOnInit  with 0.10.4.
