### ISSUE TITLE
Karma/Jasmine test & template issues.

### ISSUE THREAD

**Issue by avoliva** [dougludlow/ng2-bs3-modal#129]
I've created an app using this library. No problems, library works fine. Though when I'm trying to unit test, I'm getting these errors:

```
Failed: Uncaught (in promise): Error: Template parse errors:
'modal-body' is not a known element:
1. If 'modal-body' is an Angular component, then verify that it is part of this module.
2. If 'modal-body' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message."
```

It seems the components are not getting loaded in the tests for whatever reason, even though I've loaded the files through the `karma-conf` file. Here's how I've loaded them in `karma.conf.js`

`{ pattern: 'node_modules/ng2-bs3-modal/**/*.js', included: false, watched: false },`

Anyone know what the issue is?

**Comment by M41in4** [comment]
https://angular.io/docs/ts/latest/testing/#!#shallow-component-test Take a look at this, maybe it will help. NO_ERROR_SCHEMA tells compiler to ignore unrecognized elements and attributes, so this should solve your problem.

**Comment by avoliva** [comment]
Hey, thanks that appears to have worked! Maybe this should be put into the docs in relation to testing?

**Comment by cbruen1** [comment]
Correct link for shallow component test:
[https://angular.io/guide/testing#shallow-component-tests-with-no_errors_schema](https://angular.io/guide/testing#shallow-component-tests-with-no_errors_schema)
