### ISSUE TITLE
Animation not works as expect

### ISSUE THREAD

**Issue by kkzhang** [dougludlow/ng2-bs3-modal#130]
In a project created angular-cli, (anguliar cli version: angular-cli: 1.0.0-beta.18, angualr2 version: 2.1.2)
i also use bootstrap & jqury from npm:

    "bootstrap": "^3.3.7",
    "jquery": "^3.1.1", 

the modal can be successfully trigged, but the fadein/out animation not works, when i click to open/close, the whole page flashed, seem the fadein/out not working properly.

I try to include 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
```
to page, but nothing changed.

**Comment by dougludlow** [comment]
Sorry I've never responded to this, it's been a busy few months. I haven't seen that at all. If you're still experiencing issues, you may want to check out the [angular cli demo](https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli).
