### ISSUE TITLE
Draggable modal

### ISSUE THREAD

**Issue by sireneweb** [dougludlow/ng2-bs3-modal#133]
Hi,
is it possible to drag modal like this ?
http://stackoverflow.com/questions/27120579/jquery-draggable-with-bootstrap-modal-scroller-strange-behaviour

**Comment by dougludlow** [comment]
@sireneweb sorry I never responded to this. Things have been busy. I imagine there's a way to extend the modal to be draggable. I won't implement that feature, but I'm open to pull requests.
