### ISSUE TITLE
How to make the modal stay open

### ISSUE THREAD

**Issue by estradamarkie** [dougludlow/ng2-bs3-modal#135]
Hi,

I don't know if this is possible at all but I will ask anyway, how do I make the modal stay open even when my function for `*ngFor` function refreshes/re-trigger when `setInterval` fires in the constructor?

Say I have this code to show my item list:

Constructor setInterval to trigger the function `getItems()` every 30seconds. Every time this fires it closes the modal, I just want the lists to refresh but without closing the modal.
```
setInterval(() => {
      this.getItems();
    }, 30000);

getItems() {
   ...http.get()
   .subscribe(data => {
      this.data = data;
   })
}

<div *ngFor="let x of data">
 <modal>...</modal>
</div>```

**Comment by estradamarkie** [comment]
Nvm found a way :)

**Comment by danimality** [comment]
@estradamarkie care to share?

**Comment by wartab** [comment]
Have your modal outside of the loop. You most likely don't want to have multiple modals opened at the same time. Simply put the data you want to show in separate variables. Every time the content needs to be updated just modify those variables.
