### ISSUE TITLE
this.$modal.appendTo(...).modal is not a function, with angular-cli

### ISSUE THREAD

**Issue by born2net** [dougludlow/ng2-bs3-modal#137]
I converted from jspm to ng-cli and getting:
```
this.$modal.appendTo(...).modal is not a function, with angular-cli
```
I have loaded both jQuery and bootstrap

any suggestion?

**Comment by born2net** [comment]
fixed

**Comment by dougludlow** [comment]
What did you end up doing?

**Comment by born2net** [comment]
well I hacked it by putting in index.html
```
<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
```
seems to be a jQuery conflict issue, I am still investigating, but related to jQuery overriding something...
