### ISSUE TITLE
How to access to the child modals which are generated in the ngFor?

### ISSUE THREAD

**Issue by vdzundza** [dougludlow/ng2-bs3-modal#138]
Hi mates,

I put the modals to the ngFor and want to access to an instance inside template .

```
<modal-footer>
<button type="button" class="btn btn-default" data-dismiss="modal" (click)="ngForModal.dismiss()">No</button>
<button type="button" class="btn btn-danger" (click)="ngForModal.close(id)">Yes, remove</button>
</modal-footer>
```

**Comment by dougludlow** [comment]
@vdzundza - sure that should be as simple as using the `@ViewChildren` annotation in your component class, which is unfortunately not very well documented yet. Basically, it should look something like this:

```typescript
@ViewChildren(ModelComponent) modals: QueryList<ModelComponent>;
```

**Comment by dougludlow** [comment]
Let me know if that didn't work.
