### ISSUE TITLE
Modal Backdrop Doesn't Disappear When Changing Routes

### ISSUE THREAD

**Issue by JimTheMan** [dougludlow/ng2-bs3-modal#139]
In a handler function for my close button I have this code:

```
this.modalJoinPrivateSession.close();
this.router.navigate(['/cypher-room-v2', this.joinRoomInputText]);
```

It switches to the route and closes the modal, but the darkened backdrop is still there, staying in front of the whole page and making the new page look very dark and weird...

**Comment by dougludlow** [comment]
What did you end up doing?

**Comment by JimTheMan** [comment]
It was just a mistake by me calling modal.open() again. haha. I'm using a custom close button in the footer since I want it to do some api call and depending on the result sometimes it leaves the modal open and sometimes it closes the modal and goes to a new page. For the second case, doing something like this works for me:

```
      this.modalJoinPrivateSession.close();
      this.router.navigate(['/cypher-room-v2', this.joinRoomInputText]);
```
