### ISSUE TITLE
with ng2 beta 0.9 I get EXCEPTION: No Directive annotation found on ModalComponent

### ISSUE THREAD

**Issue by born2net** [dougludlow/ng2-bs3-modal#14]
with ng2 beta 0.9 I get EXCEPTION: No Directive annotation found on ModalComponent
works fine in 0.8
and it's odd, I am not sure why ng2 is throwing on  directive annotation missing when ModalComponent is a @Component based... mmmm did you run into this?

regards

Sean

**Comment by born2net** [comment]
has anyone tried beta0.9 with modal?

**Comment by dougludlow** [comment]
Sorry, I haven't had a chance to yet.

**Comment by born2net** [comment]
this thing really baffles me as I was looked a the ng2 change log: https://github.com/angular/angular/blob/master/CHANGELOG.md and I don't see anything that would break this in ng0.9, yet it is broken :/

**Comment by born2net** [comment]
same error in ng beat .10

**Comment by dougludlow** [comment]
I'm unable to repro this particular issue in beta.11, but I did see angular/angular/#7666 crop up.

**Comment by dougludlow** [comment]
@born2net could you post some example code or a plunkr that repro the issue?

**Comment by born2net** [comment]
I will try .11 and update on the results, regards

**Comment by born2net** [comment]
.11 fixed now tx

**Comment by dougludlow** [comment]
:thumbsup:
