### ISSUE TITLE
Web Pages freezes when options is selected from a drop-down on modal only on iPhone

### ISSUE THREAD

**Issue by MilanRaval** [dougludlow/ng2-bs3-modal#141]
In web page I have used this modal and it has one drop-down. On iPhone when I am selecting any value from drop-down it freezes the web page and it can't be un-freeze till I change orientation on iPhone. What can be the issue, how to debug ?

**Comment by dougludlow** [comment]
@MilanRaval can you provide some example code? It's hard to troubleshoot without any code.

**Comment by MilanRaval** [comment]
thanks ! 

This is how I am using modal, 

`<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()" (onDismiss)="dismissed()"
       (onOpen)="opened()" [cssClass]="cssClass" #modal>
    <modal-header [show-close]="true">
        <h4 class="modal-title">Search</h4>
    </modal-header>
    <modal-body style="font-size:medium">
        <div class="form-horizontal">
            <fieldset>               
                <div class="form-group">
                    <div class="col-sm-4 control-label">
                        <label>State</label>
                    </div>
                    <div class="col-sm-6">
                        <select id="state" name="state" class="form-control" [(ngModel)]="search.state">
                            <option value="0"></option>
                            <option value="2">Alabama</option>
                            <option value="1">Alaska</option>
                            <option value="4">Arizona</option>
                            <option value="3">Arkansas</option>
                            <option value="5">California</option>
                            <option value="6">Colorado</option>
                            <option value="7">Connecticut</option>
                            <option value="9">Delaware</option>
                            <option value="8">District of Columbia</option>
                            <option value="10">Florida</option>
                            <option value="11">Georgia</option>
                            <option value="12">Hawaii</option>
                            <option value="14">Idaho</option>
                            <option value="15">Illinois</option>
                            <option value="16">Indiana</option>
                            <option value="13">Iowa</option>
                            <option value="17">Kansas</option>
                            <option value="18">Kentucky</option>
                            <option value="19">Louisiana</option>
                            <option value="22">Maine</option>
                            <option value="21">Maryland</option>
                            <option value="20">Massachusetts</option>
                            <option value="23">Michigan</option>
                            <option value="24">Minnesota</option>
                            <option value="26">Mississippi</option>
                            <option value="25">Missouri</option>
                            <option value="27">Montana</option>
                            <option value="30">Nebraska</option>
                            <option value="34">Nevada</option>
                            <option value="31">New Hampshire</option>
                            <option value="32">New Jersey</option>
                            <option value="33">New Mexico</option>
                            <option value="35">New York</option>
                            <option value="28">North Carolina</option>
                            <option value="29">North Dakota</option>
                            <option value="36">Ohio</option>
                            <option value="37">Oklahoma</option>
                            <option value="38">Oregon</option>
                            <option value="39">Pennsylvania</option>
                            <option value="40">Rhode Island</option>
                            <option value="41">South Carolina</option>
                            <option value="42">South Dakota</option>
                            <option value="43">Tennessee</option>
                            <option value="44">Texas</option>
                            <option value="45">Utah</option>
                            <option value="47">Vermont</option>
                            <option value="46">Virginia</option>
                            <option value="48">Washington</option>
                            <option value="50">West Virginia</option>
                            <option value="49">Wisconsin</option>
                            <option value="51">Wyoming</option>
                        </select>
                    </div>
                </div>               
                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-8 voffset10">
                        <button class="btn btn-default" (click)="resetSearch()" style="vertical-align:bottom">Reset</button>
                        <button class="btn btn-primary" style="vertical-align:bottom" (click)="search()">Search</button>
                    </div>
                </div>
            </fieldset>
        </div>
    </modal-body>
</modal>`

**Comment by dougludlow** [comment]
@MilanRaval sorry for dropping the ball on this one. If you're still having issues feel free to reopen.
