### ISSUE TITLE
How to open the md2-dialog from .ts file instead of html file in angular2

### ISSUE THREAD

**Issue by aminsmartsense** [dougludlow/ng2-bs3-modal#142]
I have one view file. In which I have two md2-dialog . one for add data and second for edit data. On edit button of each row. I want to first get the data as respective to the data and then I want to open the dialog.

I want to open dialog after API's  successful response. Please provide solution.

**Comment by dougludlow** [comment]
@aminsmartsense feel free to take a look at the project's [readme](https://github.com/dougludlow/ng2-bs3-modal#opening-and-closing-the-modal-from-a-parent-component), it show's exactly how to do this:

```typescript
import { Component, ViewChild } from '@angular/core';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';

@Component({
    selector: 'parent-component',
    template: `
        <modal #myModal>
            ...
        </modal>
    `
})
export class ParentComponent {
    @ViewChild('myModal')
    modal: ModalComponent;

    close() {
        this.modal.close();
    }

    open() {
        this.modal.open();
    }
}
```
