### ISSUE TITLE
Should not close the modal if I click anywhere else

### ISSUE THREAD

**Issue by nirav-upadhyay** [dougludlow/ng2-bs3-modal#145]
Hi,

I want to show the backdrop and should close the popup only on clicking the button Close/OK, currently when i click anywhere else on screen it closes the modal.

Regards,
Nirav

**Comment by dougludlow** [comment]
@nirav-upadhyay you can do this by settings `backdrop="'static'"`. The [docs](https://github.com/dougludlow/ng2-bs3-modal#static-modal) show an example of this: 

```
<modal #modal [keyboard]="false" [backdrop]="'static'">
    <modal-header [show-close]="false">
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    <modal-body>
        Hello World!
    </modal-body>
    <modal-footer [show-default-buttons]="true"></modal-footer>
</modal>
```

**Comment by atalis** [comment]
The two functions are completely unrelated.  Dismissing a dialog on Esc is a universal approach.  The user has to take an explicit action, just like clicking the Cancel button.

However, whether or not a dialog is closed when the user clicks outside of it is dictated by a business case.  For forms in dialogs, a lot of the time, it is not desirable for the dialog to go away if the user clicks outside of the dialog by accident while navigating from field to field with a mouse.

Could you possibly implement a closeOnOutsideClick option, similar to ng2-modal?

Thanks,
Anna
