### ISSUE TITLE
ng2-bs4-modal : Open/close from parent : Could not read property open of undefined

### ISSUE THREAD

**Issue by dlarr** [dougludlow/ng2-bs3-modal#146]
Hello,

I have been trying this modal. Thank you very much for this work.

I simply put the default modal example, in my template. It works pretty well if I use :
`<button type="button" class="btn btn-default" (click)="modal.open()">Open me!</button>`

Though I want to use : 
`div class="f-right fa fa-user-plus clickable" (click)="addUser()"></div>`

And then in my parent component : 
```
    addUser() : void {
        this.modal.open();
    }
```

I get this error : 
![image](https://cloud.githubusercontent.com/assets/2865021/21525638/e4a273d6-cd1e-11e6-81ed-a342ccc1e8f0.png)

Any input would be greatly appreciated :)

Best Regards,
Denis.

**Comment by dlarr** [comment]
Hello, 

Dumb me : in fact I was declaring the modal like this :
```
    @ViewChild('myModal')
    protected modal: ModalComponent; 
```

And in HTML i Was declaring this : 
```
<modal #modal [animation]="animation" (onClose)="closed()" (onDismiss)="dismissed()" (onOpen)="opened()">
...
</modal>
```

Obviously myModal must match this #modal so I have changed to #myModal.

You can close :)

Great job, nice lib by the way : thank you so much.

**Comment by dougludlow** [comment]
:thumbsup:
