### ISSUE TITLE
Parent width decrease after close

### ISSUE THREAD

**Issue by Ferhatos** [dougludlow/ng2-bs3-modal#150]
Hello,
With angular 2 and routing, open many modal at more than 3 levels is not working.
As a workaround, I close modal of previous level before open next.
My problem is :
- If I close programatically last opened modal before open next, It's working fine. But when I close the last opened modal (the only opened), the "main-cointainer" decrease the witdh per 17pix !

To reproduce this issue, just open two modal. When we close the last one, the "main-container" decrease the witdh. When we close the second modal, "main-container" witdh return to original value.

Any one know what happened with "main-container".width ?

Thank you.

**Comment by dougludlow** [comment]
@Ferhatos thanks for reporting this. I'm a little slammed at the moment, but I'll take a look at it when I get a chance.

**Comment by dougludlow** [comment]
Closing since this is so old. Feel free to reopen if you are still experiencing issues.
