### ISSUE TITLE
Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by alpeshv** [dougludlow/ng2-bs3-modal#151]
Getting "Unexpected value 'undefined' imported by the module 'AppModule'". 

`import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';` imports Ng2Bs3ModalModule as undefined. 

My systemjs.config.js has got the following mapping.
`'ng2-bs3-modal/ng2-bs3-modal': 'npm:ng2-bs3-modal/bundles/ng2-bs3-modal.js'`

Not sure if there is anything changed in the latest version or its just me doing something silly.

**Comment by winni4eva** [comment]
try 
---------------------------------------
import { MODAL_DIRECTIVES, ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
declarations: [ AppComponent, MODAL_DIRECTIVES]
---------------------------------------

But not working for me now. using angular 2.2.0

**Comment by alpeshv** [comment]
@winni4eva Thanks. I am using 2.4.0 so that could be the issue. 

I am not using this package anymore. I have created my own simple component for modal.

**Comment by dougludlow** [comment]
Hi guys, I haven't tested with the latest version of Angular. I don't have any active projects at the moment using this modal. I'll take a look when I get a moment. In the mean time if anyone wants to try to take a stab at figuring out what's going on, that would be helpful.

**Comment by ApoorvBarwa** [comment]
Hi ... i am running Angular 2 with the following configuration...

@angular/cli: 1.0.0
node: 6.10.0
os: win32 x64
@angular/common: 2.2.1
@angular/compiler: 2.2.1
@angular/core: 2.2.1
@angular/forms: 2.2.1
@angular/http: 2.2.1
@angular/platform-browser: 2.2.1
@angular/platform-browser-dynamic: 2.2.1
@angular/router: 3.2.1
@angular/compiler-cli: 2.2.1

i have installed the package mentioned by you and gives me the below error

My app.module.ts file

```
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
imports: [
  
    BsModalModule,
```

the above give me an error 
`Cannot find name 'BsModalModule'
`
i did a grep on the folder node_modules/ng2-bs3-modal with the following command .

`find . -type f -exec grep "BsModalModule" {} \;`

and i dont get any matching patterns ....

It seems to me that we are trying to import something which is not present ... not sure though
