### ISSUE TITLE
Background page scrolls to top while opening dialog

### ISSUE THREAD

**Issue by MilanRaval** [dougludlow/ng2-bs3-modal#154]
This dialog scrolls background page to top, tried setting below in css , but it didn't work 
body.modal-open {
    overflow: visible;
}

**Comment by VikrantGodse** [comment]
This Works for me perfectly.It prevents background-scroll
body.modal-open {
overflow: visible;
}

**Comment by vicabelotelova** [comment]
now appears two scrolls on the page
