### ISSUE TITLE
Set body content using [content]="html_code" or something like that

### ISSUE THREAD

**Issue by julianpoemp** [dougludlow/ng2-bs3-modal#155]
Is there a way how I can set the modal-content using an directive like [content] or something like that?
I have to set the html code of the body content dynamically.
Here is an example of code:
`
<modal #modal_delete>
    <modal-header>
        <h4 class="modal-title">Delete</h4>
    </modal-header>
    <modal-body [content]="<b>Really?</b>">
    </modal-body>
    <modal-footer>
    </modal-footer>
</modal>
`

**Comment by dougludlow** [comment]
@julianpoemp yes, simply put dynamic content in the modal body. Using your example: 

```html
ere is an example of code:
<modal #modal_delete>
    <modal-header>
        <h4 class="modal-title">Delete</h4>
    </modal-header>
    <modal-body>
        <my-dynamic-component [value]="myModel" />
        {{ otherDynamicStuff }}
    </modal-body>
    <modal-footer>
    </modal-footer>
</modal>
```

**Comment by julianpoemp** [comment]
Thank you. I could solve this like that:
```
<modal #modal_delete>
    <modal-header>
        <h4 class="modal-title">Delete</h4>
    </modal-header>
    <modal-body>
        <div [innerHTML]="html_code"></div>
    </modal-body>
    <modal-footer>
    </modal-footer>
</modal>
```
