### ISSUE TITLE
Error: System is not defined

### ISSUE THREAD

**Issue by Sean-Brown** [dougludlow/ng2-bs3-modal#156]
My project is an angular-cli project using the rc.1 version of the cli. I included the component to app.module as instructed, and added the javascript script to the "scripts" section of the .angular-cli.json file. However, when I go to run the application I open the console and notice:
![image](https://cloud.githubusercontent.com/assets/1503131/23760844/f18a0244-04be-11e7-9bfe-5c0dd7319038.png)

For reference, I have no file and no location in the code  that does "System.config()" like your instructions reference, and I noticed that nowhere in your [sample](https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli) does it do "System.config()", so this error confuses me.

Is there any more info you need to diagnose this? To me it seems like a simple mis-configuration but I cannot tell what I am missing.

**Comment by dougludlow** [comment]
> ...and added the javascript script to the "scripts" section of the .angular-cli.json file

@Sean-Brown what scripts did you include? The `./bundles/ng2-bs3-modal.js` is in SystemJS. Perhaps you're including that instead of the main `./ng2-bs3-modal.js` which should be UMD.

**Comment by Sean-Brown** [comment]
Correct, I did import from ./bundles. I changed the import and I get a new error:
![image](https://cloud.githubusercontent.com/assets/1503131/23771081/ad2fd8b0-04e3-11e7-925c-68bc4661906d.png)

Do I need to import nodejs or something?

**Comment by dougludlow** [comment]
@Sean-Brown to be honest, I'm not real familiar with webpack. But I did have a working demo for it here: https://github.com/dougludlow/ng2-bs3-modal-demo-webpack

**Comment by dougludlow** [comment]
Whoops, misread that. I have an angular-cli demo here: https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli

**Comment by Sean-Brown** [comment]
Thanks I was following that example and I noticed that it does not have the error, so I'm doing something wrong. I'll update when I find out exactly what.

**Comment by jharrys** [comment]
Sean-Brown - any luck? I followed the solution and also got the new ReferenceError.

**Comment by Sean-Brown** [comment]
No I ended up using [ng2-bootstrap modal](https://valor-software.com/ng2-bootstrap/#/modals) since I already had that included in the project and [angular2-modal](https://github.com/shlomiassaf/angular2-modal) for other dynamic modals.

**Comment by dougludlow** [comment]
@jharrys out of curiousity, what does your import statement look like?

**Comment by jharrys** [comment]
@dougludlow I assume you mean my scripts entry in .angular-cli.json:
      "scripts": [
        "../node_modules/ag-grid/dist/ag-grid.min.js",
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/js/modal.js",
        "../node_modules/ng2-bs3-modal/ng2-bs3-modal.js",
        "../node_modules/materialize-css/dist/js/materialize.min.js"

did you mean something else?

**Comment by dougludlow** [comment]
No, I mean the statement you use to import the Ng2Bs3ModalModule. Does it look like this:

```
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
```

**Comment by dougludlow** [comment]
@jharrys also, you shouldn't have to include it in the scripts.

**Comment by dougludlow** [comment]
@jharrys - take a look at the angular-cli.json from the sample project: https://github.com/dougludlow/ng2-bs3-modal-demo-angular-cli/blob/master/angular-cli.json#L24-L27

**Comment by jharrys** [comment]
@dougludlow that's what I thought when looking at the sample project, but every time I remove it, the modal doesn't show (so I must be doing something wrong).

my import statements all are:
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';

**Comment by dougludlow** [comment]
@jharrys kk, just making sure it wasn't 

```
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal';
```

I'll need to go back through the angular-cli demo and update it to use angular-cli@1, that might be the issue.

**Comment by ivange94** [comment]
Removing this  "../node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.min.js" from angular-cli.json scripts fixed the issue for me and the modal still shows.

**Comment by marcosvolpato** [comment]
thanks a lot ivange94
