### ISSUE TITLE
Pre-dismiss hook

### ISSUE THREAD

**Issue by Sean-Brown** [dougludlow/ng2-bs3-modal#157]
Is there a way to hook into the pre-dismiss event (or some equivalent event that gets fired BEFORE the modal is closed)? My scenario is that I have a modal form: if the form is dirty and the user attempts to exit, then I want to pop up a confirmation modal. 

I can listen to "OnDismiss" and "OnClose" events to nearly achieve this functionality, but by the point these hooks are reached, the modal has already been closed and is no longer displayed (I want it displayed). 

Is there a convenient way to hook into an event BEFORE the dialog is closed (with the opportunity to cancel the close event)?

**Comment by dougludlow** [comment]
@Sean-Brown this component is basically a wrapper around the [bootstrap modal api](http://getbootstrap.com/javascript/#modals-events). However, I'm only listening to the 'shown' and 'hidden' events at this point. I haven't added support for any other events yet, but contributions are welcome. 

Resources:
[Modal Events](http://getbootstrap.com/javascript/#modals-events)
[javascript bootstrap modal - cancel closing](http://stackoverflow.com/questions/21228880/javascript-bootstrap-modal-cancel-closing)

**Comment by Sean-Brown** [comment]
I'm gonna try to do that then submit a PR. I did notice that the app doesn't build after a fresh pull down, i.e. I cloned the repo onto my pc and ran `npm i`, and that command did not succeed:
![image](https://cloud.githubusercontent.com/assets/1503131/23773038/78397302-04eb-11e7-97cc-cb447ed9d217.png)

**Comment by dougludlow** [comment]
@Sean-Brown bummer, I'll have to give it a try here in a little while. My guess is I didn't lock down a dependency and it updated and broke whatever I was using it for.

**Comment by Sean-Brown** [comment]
I got around the build error by updating the @angular/compiler-cli dependency to "^2.0.0"

**Comment by dougludlow** [comment]
This should be available in v0.12. The `onShow` and `onHide` events were added. See the readme and the demo for details.
