### ISSUE TITLE
Running ng test on my application gives me System not defined

### ISSUE THREAD

**Issue by prabhurangan** [dougludlow/ng2-bs3-modal#158]
Hi Team,

I am using ng2-bs3-modal for my application; when i tried to run ng test it throws me this error.  Appreciate your help on this.

Uncaught ReferenceError: System is not defined at node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.js:18

**Comment by alissonschneiderr** [comment]
Hi, I have the same error.

`Uncaught ReferenceError: System is not defined
    at eval (eval at webpackJsonp../node_modules/script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:18:1)
    at eval (<anonymous>)
    at webpackJsonp../node_modules/script-loader/addScript.js.module.exports (addScript.js:9)
    at Object../node_modules/script-loader/index.js!./node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.js (ng2-bs3-modal.js?4118:1)
    at __webpack_require__ (bootstrap 6414c10…:54)
    at Object.2 (scripts.bundle.js:187)
    at __webpack_require__ (bootstrap 6414c10…:54)
    at webpackJsonpCallback (bootstrap 6414c10…:25)
    at scripts.bundle.js:1`

in angular-cli I have this:

`
"scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/toastr/build/toastr.min.js",
        "../node_modules/switchery/standalone/switchery.js",
        "../node_modules/moment/moment.js",
        "../node_modules/metismenu/dist/metisMenu.js",
        "../node_modules/jquery-slimscroll/jquery.slimscroll.js",
        "assets/css/vendor/inspina/js/inspina.js",
        "../node_modules/fullcalendar/dist/fullcalendar.min.js",
        "../node_modules/fullcalendar/dist/locale/pt-br.js",
        "../node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.js"
      ]
`
on module

`
// nativos
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

// componentes
import { CalendarioComponent } from './calendario.component';

// modulos
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal';

@NgModule({
  imports: [
    CommonModule,
    Ng2Bs3ModalModule
  ],
  declarations: [
    CalendarioComponent
  ],
  exports: [
    CalendarioComponent
  ]
})
export class CalendarioModule { }
`

**Comment by dougludlow** [comment]
@alissonschneiderr the `node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.js` script is a systemjs bundle. If you're using angular-cli/webpack you don't want to include it. You should just need to import the module like so:

```
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
```

**Comment by alissonschneiderr** [comment]
Thanks @dougludlow , solved it.
