### ISSUE TITLE
Creating a global login modal that can be called from any other component

### ISSUE THREAD

**Issue by leighmillard** [dougludlow/ng2-bs3-modal#159]
Hi,

I have a project with the standard header, router-content, footer type setup.

I have a modal which contains a user login form but I need to be able to open this from buttons in the header and footer (as well as various other places). What is the best way to achieve this? 

<app-header></app-header>
<main>
    <router-outlet></router-outlet>
</main>
<app-footer></app-footer>

Based on the above I have the standard header/footer code which is loaded once. 

I have hunted around on Stackoverflow and looked at the examples in the readme but nothing is working for me - I must admit I am new to ng2. I can see examples in previous question but these go back to mid 2016 and the code in them errors for me so I assume ng has moved on since.

Regards
Leigh

**Comment by dougludlow** [comment]
@leighmillard probably just exposing the modal on a higher level component, such as your root component and maybe creating a service that has a handle on it to open and close it would work. I can't think of any other solutions off the top of my head right now...
