### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by amihailes** [dougludlow/ng2-bs3-modal#160]
Hi,

Is it possible to have an Angular 4 based build?

Thanks in advance,

Adrian

**Comment by dougludlow** [comment]
@amihailes ha ha, yes, it only came out last night, but I'm working on it.

**Comment by amihailes** [comment]
Good news!

**Comment by ChadiEM** [comment]
It's perhaps the opportunity to rename the project to something like angular-bs3-modal. With Angular 4, Google is suggesting to remove the Angular version from the libraries.

**Comment by assaulter** [comment]
oh, ng2-bootstrap was renamed to ngx-bootstrap.

**Comment by grichards23** [comment]
I just tried upgrading my project to angular 4, before doing so I made sure to have the latest ng2-b3-modal component.

npm is throwing peer dependency warnings that ng2-bs3-modal@0.10.4 requires angular ^2.0.0 versions.

Can I safely ignore these?

**Comment by dougludlow** [comment]
@grichards23 - I believe you can. I'm working on trying to get an Angular v4 version out, just haven't had a whole lot of time lately.

**Comment by wartab** [comment]
@grichards23 I have no trouble besides the peer dependencies not meeting the requirements. It works perfectly fine!

**Comment by arun-awnics** [comment]
Hey @dougludlow Can you please upgrade the repo to support angular4 and bs4? I am using ng2-bs3-modal in my project which uses angular4. I am planning on upgrading my project to BS4. So it will be better if ng2-bs3-modal supports all the dependencies. Thank you in advance.

**Comment by Stefan-Aurea** [comment]
Hey @dougludlow , I am curious as to how you're using `ng2-bs3-modal` with angular4 given that the current version has a `peerDependency` on `angular@^2.0.0`

...this is in fact what is blocking me right now.

**Comment by wartab** [comment]
Peer dependency error messages are warnings, not errors. You can safely ignore them.

**Comment by Stefan-Aurea** [comment]
Got it, thanks @wartab, I guess I'm just one of those perfectionists who hate warnings ;) I like clean output :)

**Comment by wartab** [comment]
It's clean if you close your eyes :)

**Comment by wartab** [comment]
But I agree, the peer-dependencies should be ^2.0.0 || ^4.0.0

**Comment by amitdahan** [comment]
@dougludlow any news? Last we heard of this was April :)

**Comment by equipe404** [comment]
It works but the warnings make it impossible to use npm shrinkwrap.

Peer dependencies should be ^2.0.0 || ^4.0.0 and that would fix the issue.

**Comment by marslan2037** [comment]
any solution for this?

**Comment by darekurlik** [comment]
+1 Please fix it as suggested by equipe404 

have problems as follows: 
npm ERR! peer invalid: @angular/common@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/compiler@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/core@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/platform-browser@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/platform-browser-dynamic@^2.0.0, required by ng2-bs3-modal@0.11.1

**Comment by darekurlik** [comment]
+1 Please fix it as suggested by equipe404 

have problems as follows: 
npm ERR! peer invalid: @angular/common@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/compiler@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/core@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/platform-browser@^2.0.0, required by ng2-bs3-modal@0.11.1
npm ERR! peer invalid: @angular/platform-browser-dynamic@^2.0.0, required by ng2-bs3-modal@0.11.1

**Comment by Stefan-Aurea** [comment]
This seems already fixed on Master... any chance it can be released?

**Comment by dougludlow** [comment]
@Stefan-Aurea I've got it released finally as v0.11.5. Enjoy.

**Comment by Stefan-Aurea** [comment]
Awesome! Thank you very much @dougludlow
