### ISSUE TITLE
Ng2-bs3-modal with canDeactivate use without a promise?

### ISSUE THREAD

**Issue by Bigless27** [dougludlow/ng2-bs3-modal#164]
```
canDeactivate() {
      if (this.changedForm && this.currentForm.dirty){
        this.modal.open()
        return new Promise((resolve) => {
          this.modal.onClose.subscribe(res => {
            resolve(true)
          })
          this.modal.onDismiss.subscribe(res => {
            resolve(false)
          })
        })
      }
      else{ 
        return true
      }
    }
```

This is how I'm currently checking what the user selects to see whether I navigate away from the page or not. Is there a better way to do this without using a promise?

**Comment by dougludlow** [comment]
@Bigless27 honestly, this is probably a better question for StackOverflow. This seems like the right approach to me. I can't think of a way to do it without a promise.

Maybe using router events? Catch NavigationStart or whatever, cancel it, but store the URL, then prompt and then navigate again if they confirm? Sounds pretty complicated. Not sure if it would even work.

**Comment by Bigless27** [comment]
@dougludlow Thank you for your response!
