### ISSUE TITLE
(index):37 Error: core_1.Input is not a function   Evaluating http://localhost:3000/ng2-bs3-modal/components/modal   Evaluating http://localhost:3000/ng2-bs3-modal/ng2-bs3-modal   Evaluating http://localhost:3000/app/app.module.js   Evaluating http://localhost:3000/app/main.js

### ISSUE THREAD

**Issue by Rameshvenkat** [dougludlow/ng2-bs3-modal#168]
Hi I am getting below error message in browser when i import the ng2-bs3-modal in app.module.ts file.
can you help me why would this happen?

(index):37 Error: core_1.Input is not a function
  Evaluating http://localhost:3000/ng2-bs3-modal/components/modal
  Evaluating http://localhost:3000/ng2-bs3-modal/ng2-bs3-modal
  Evaluating http://localhost:3000/app/app.module.js
  Evaluating http://localhost:3000/app/main.js

expecting your response

**Comment by dougludlow** [comment]
@Rameshvenkat sorry for never getting back to you on this. Feel free to reopen if you're still seeing errors.
