### ISSUE TITLE
Parent Modal doesn't scroll after child modal closed

### ISSUE THREAD

**Issue by hassan-ahmed** [dougludlow/ng2-bs3-modal#170]
So,

I have a parent modal having height > window height, everything works fine.
Now I open another child modal within this parent modal, and when I close this child modal the parent doesn't scroll anymore.

Any Angular 2 specific solution to this ? 

jQuery solution ref: http://stackoverflow.com/questions/37153278/bootstrap-modal-doesnt-scroll-after-child-modal-closed

**Comment by arun-awnics** [comment]
@hassan-ahmed So, a simple solution to this issue would be CSS. 
I have used this: 
`modal {
    overflow: auto !important;
}`

**Comment by dougludlow** [comment]
Duplicate of #57.
