### ISSUE TITLE
Override modal-content styles

### ISSUE THREAD

**Issue by grichards23** [dougludlow/ng2-bs3-modal#171]
I've successfully overridden styles for modal-body and modal-header where needed, however, the same approach doesn't appear to work for modal-content.

I have a need to make the background transparent, hide the borders/box shadow defaults of the bootstrap modal.

I've hacked these styles in manually via google developer tools and they work as expected, however when I create a class and specify a cssClass property on the ng2-bs3-modal, doesn't seem as the modal applies the styles as expected.

I sat with a "css expert" and we tried 19 different ways to accomplish (using the id of the element, targeting the html elements directly etc)

What am I missing?

Simple code below:

```
<style>
   div.transparent-modal .modal-content {
      background: transparent !important;
      border: none !important;
      -moz-box-shadow: none !important;
      -webkit-box-shadow: none !important; 
      box-shadow: none !important;   
   }
</style>
```

```
<modal #processingModal cssClass="transparent-modal" keyboard="false" backdrop="static" id="processingModal">
   <modal-body>
      <div class="row">
         <div class="col-xs-12">
            Hello World!
         </div>
      </div>
   </modal-body>
</modal>
```

**Comment by grichards23** [comment]
Nevermind, for testing purposes I was adding the style block directly into my component just above the modal element.

When I move the class/styles out to the site's style sheet, it worked as expected.

**Comment by dougludlow** [comment]
Cool, glad you got it figured out.

**Comment by uncarlo** [comment]
I'm trying this but it doesn't work for me. I'm using SASS; do you think there's any difference?

**Comment by dougludlow** [comment]
No there should be any difference. What does your code look like, how are
you including your sass?
