### ISSUE TITLE
call modal.open() inside another function ?

### ISSUE THREAD

**Issue by SELKHENIFER** [dougludlow/ng2-bs3-modal#173]
Hi, 
How can I use 'modal.open()' inside another function, I dont want to call it direclty on button click, but after the fucntion executes!

Can anyone help please?

**Comment by ColeBeckwith** [comment]
Not sure about calling it from within a component function, but you can try:

`(click)="firstFunction(); modal.open()"`

**Comment by dougludlow** [comment]
@SELKHENIFER - sorry I missed this somehow. Please check out the example in the readme: 

https://github.com/dougludlow/ng2-bs3-modal#opening-and-closing-the-modal-from-a-parent-component
