### ISSUE TITLE
Not working with angular 4

### ISSUE THREAD

**Issue by sheetaldshivdas** [dougludlow/ng2-bs3-modal#176]

**Comment by wartab** [comment]
It does.

**Comment by arun-awnics** [comment]
It works with angular4.

**Comment by sheetaldshivdas** [comment]
Yes Please ignore!!!

**Comment by wartab** [comment]
Nobody is ignoring you, if you do not give more details than "Not working", nobody can nor wants to help you.

**Comment by sheetaldshivdas** [comment]
Lol you got me wrong!!! I meant to say it worked for me and ignore my issue not me hehe...

**Comment by wartab** [comment]
All good then, glad you got it figured out!
