### ISSUE TITLE
ERROR in Ng2Bs3ModalModule is not an NgModule - angular cli, angular 4

### ISSUE THREAD

**Issue by vaidd4** [dougludlow/ng2-bs3-modal#177]
I'm on an **angular-cli** project with Angular 4.
Running `ng serve` gives this error : 
```
Hash: 6941a848791c0fb318c5
Time: 48865ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 4.07 MB {3} [initial] [rendered]
chunk    {1} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 167 kB {4} [initial] [rendered]
chunk    {2} styles.bundle.js, styles.bundle.js.map (styles) 65.6 kB {4} [initial] [rendered]
chunk    {3} vendor.bundle.js, vendor.bundle.js.map (vendor) 7.06 MB [initial] [rendered]
chunk    {4} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in Ng2Bs3ModalModule is not an NgModule
webpack: Failed to compile.
```
in `package.json`
```JS
"dependencies": {
  "@angular/core": "4.0.0",
  "@angular/forms": "4.0.0",
  "@angular/http": "4.0.0",
  ...
  "bootstrap": "3.3.7",
  "jquery": "2.2.4",
  ...
  "ng2-bs3-modal": "0.8.1",
  ...
},
"devDependencies": {
  "@angular/cli": "1.0.0",
  ...
}
```
in `app.module.ts`
```JS
import {Ng2Bs3ModalModule} from 'ng2-bs3-modal';
...
@NgModule({
  imports: [
    ...
    Ng2Bs3ModalModule,
    ...
  ],
  declarations: [...],
  providers: [...],
  bootstrap: [AppComponent]
```

**Comment by vaidd4** [comment]
After some research I found this : 
It might be related with AOT compilation.

See this issue https://github.com/angular/angular-cli/issues/3426

And may be the comments below, in this issue : angular/angular#11262
https://github.com/angular/angular/issues/11262#issuecomment-244472000
https://github.com/angular/angular/issues/11262#issuecomment-244489405

This might help : https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#compile

#176 May be related but no information was given.

**Comment by wartab** [comment]
You might find a work around in #143 that works for you.

**Comment by vaidd4** [comment]
If I launch `ng serve` a first time and then I modify any file, webpack will recompile and will not give the error.

With https://github.com/dougludlow/ng2-bs3-modal/issues/143#issuecomment-277515953, it gives me the same error (`is not a NgModule`).

With https://github.com/dougludlow/ng2-bs3-modal/issues/143#issuecomment-290730273 I get this error : 
```
ERROR in [...]/node_modules/ng2-bs3-modal/src/ng2-bs3-modal/components/modal-instance.ts (74,47): Operator '===' cannot be applied to types 'ModalResult.Close | ModalResult.Dismiss' and 'ModalResult.None'.
```
And if I try to correct the line in `/modal-instance.ts/modal-instance.ts` : 
```
let result = (!this.result || this.result === ModalResult.None)
```
to
```
let result = (this.result === ModalResult.None)
```
I'm not getting compile error anymore.

Not suitable for my project as I'm not working alone on it.

**Comment by vaidd4** [comment]
Wow, I don't know why I didn't checked that before but the last version of `ng2-bs3-modal` is **0.10.4** and I was using **0.8.1**

Updating the version resolved it...

**Comment by wartab** [comment]
Can happen :) Glad you got it figured out. If I remember well, I had the same issue with that error message as well.
