### ISSUE TITLE
Having problems with the default tabIndex=-1 in chrome, firefox, IE

### ISSUE THREAD

**Issue by ranjik2909** [dougludlow/ng2-bs3-modal#181]
I am trying to open a modal on loading an angular component. If I hit esc immediately after the modal is opened, it closes even when the keyboard property is set to false. So, by researching a little I found out that the default tabIndex on the modal was -1. I tried assigning [attr.tabIndex]="null". By doing that, I was able to keep the modal static after hitting the esc key. But, it only works in chrome not in IE and Firefox.

HTML:

<modal #modal [keyboard]="false" [backdrop]="'static'">
    <modal-header>
        <h4 class="modal-title">Message</h4>
    </modal-header>
    <modal-body>
        <div *ngFor="let message of messages">
            <p>{{message}}</p>
        </div>
    </modal-body>
    <modal-footer>
        <button type="button" class="btn btn-default" data-dismiss="modal 
        (click)="continue()">Continue</button>
    </modal-footer>
</modal>

ts:
    @ViewChild('modal')
    modal: ModalComponent;

    close() {
        this.modal.close();
    }

    open() {
        this.modal.open();
    }

    ngOnInit() {
        this.modal.open();
    }

Please help me fix this. 
I am using angular 4 with ng2-bs3-modal@0.10.4, angular-cli webpack.

Thank you.

**Comment by dougludlow** [comment]
This has been fixed in v0.11
