### ISSUE TITLE
ERROR TypeError: Cannot read property 'dismiss' of undefined

### ISSUE THREAD

**Issue by bob1457** [dougludlow/ng2-bs3-modal#183]
I have a modal dialog with a form and am trying to close/dismiss the modal dialog in its component ts file after submitting the form. But I got error of "Cannot read property 'dismiss' of undefined", and modal was not closed.

Here is my code:

request-form.component.ts:
```typescript
import { Component, ElementRef, Input, OnInit, OnDestroy } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { Http, Response } from '@angular/http';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';
import { ProductService } from '../../shared/services/index';

@Component({
  moduleId: module.id.toString(),
  selector: 'app-request-form',
  templateUrl: './request-form.component.html',
  styleUrls: ['./request-form.component.scss']
})
export class RequestFormComponent {
    modal: ModalComponent;

    onSubmit(){

        this.productService.SendRequest(this.requestForm.value)
            .subscribe(data => {
                //processing logic
          
                this.modal.dismiss();
        },
        error => {
            //processing logic
        });
    }
}
```

Although I read the previous postings on this issue, I still cannot get it work. My understanding here is not closing it from the parent, it is just from itself. Even I tried to move all form code to the parent html and tried to close the modal from the parent following your instructions from the github, it always gives me the same error.

Maybe the libraries are not loaded properly. I loaded jquery and bootstrap using cdn insidie the index.html near the closing tag of </body>as follows:

index.htm:
```html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
```
ng2-bs-3-modal was loaded and imported from app.module.ts

**Comment by dougludlow** [comment]
@bob1457 you're close, compare with https://github.com/dougludlow/ng2-bs3-modal#opening-and-closing-the-modal-from-a-parent-component

You're missing the following annotation on the `modal` property:
```typescript
@Component({
    ...
})
export class RequestFormComponent {
    @ViewChild('myModal')
    modal: ModalComponent;
    ...
}
```

Where `myModal` is the template variable on the modal in the template.

Let me know if that makes sense.

**Comment by bob1457** [comment]
Thanks. 
The question is my modal dialog is in a component, the code to close it is in the component.ts file, is this still the parent/child relation?

Even I put @ViewChild, I still have the error.

I also tried moving the form in the modal component to the parent component, and close the dialog from parent component.ts file. Same error. I must have missing something else?

**Comment by dougludlow** [comment]
@bob1457 can you show a little more of your code. Kinda hard to shoot in the dark. 🔫 🌔

**Comment by bob1457** [comment]
Here are the code attached:

The parent component is product-ezq.component.ts, and the modal is inside product-ezq.component.html.
bootstrap and jquery loaded using cdn in index.html.

Thanks. By the way, I am using VS Code, when debugging the code, it seems the problem was in bootstrap script, maybe the version of it matters?

Not sure I pasted the code properly, but I drop you a file with the code
[code.txt](https://github.com/dougludlow/ng2-bs3-modal/files/1028233/code.txt


`

**Comment by bob1457** [comment]
No worries, I got it work. probably the loading sequence matters.

Thanks a lot for that.
