### ISSUE TITLE
mode/modal-header/modal-body/modal-footer is an Angular component

### ISSUE THREAD

**Issue by AndroidHitchhiking** [dougludlow/ng2-bs3-modal#186]
I did every configuration as mention but I always get his error when I paste the hello world popup code as given in sample, Trace is below - 

ERROR Error: Uncaught (in promise): Error: Template parse errors:
'modal-header' is not a known element:
1. If 'modal-header' is an Angular component, then verify that it is part of this module.
2. If 'modal-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

<modal #modal>
    [ERROR ->]<modal-header >
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
"): ng:///AssetModule/ListassetComponent.html@84:4
'modal-body' is not a known element:
1. If 'modal-body' is an Angular component, then verify that it is part of this module.
2. If 'modal-body' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    [ERROR ->]<modal-body>
        Hello World!
    </modal-body>
"): ng:///AssetModule/ListassetComponent.html@87:4
Can't bind to 'show-default-buttons' since it isn't a known property of 'modal-footer'.
1. If 'modal-footer' is an Angular component and it has 'show-default-buttons' input, then verify that it is part of this module.
2. If 'modal-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        Hello World!
    </modal-body>
    <modal-footer [ERROR ->][show-default-buttons]="true"></modal-footer>
</modal>

"): ng:///AssetModule/ListassetComponent.html@90:18
'modal-footer' is not a known element:
1. If 'modal-footer' is an Angular component, then verify that it is part of this module.
2. If 'modal-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        Hello World!
    </modal-body>
    [ERROR ->]<modal-footer [show-default-buttons]="true"></modal-footer>
</modal>

"): ng:///AssetModule/ListassetComponent.html@90:4
'modal' is not a known element:
1. If 'modal' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
   <button type="button" class="btn btn-default" (click)="modal.open()">Open me!</button>

[ERROR ->]<modal #modal>
    <modal-header >
        <h4 class="modal-title">I'm a modal!</h4>
"): ng:///AssetModule/ListassetComponent.html@83:0
Error: Template parse errors:
'modal-header' is not a known element:
1. If 'modal-header' is an Angular component, then verify that it is part of this module.
2. If 'modal-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

<modal #modal>
    [ERROR ->]<modal-header >
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
"): ng:///AssetModule/ListassetComponent.html@84:4
'modal-body' is not a known element:
1. If 'modal-body' is an Angular component, then verify that it is part of this module.
2. If 'modal-body' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    [ERROR ->]<modal-body>
        Hello World!
    </modal-body>
"): ng:///AssetModule/ListassetComponent.html@87:4
Can't bind to 'show-default-buttons' since it isn't a known property of 'modal-footer'.
1. If 'modal-footer' is an Angular component and it has 'show-default-buttons' input, then verify that it is part of this module.
2. If 'modal-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
        Hello World!
    </modal-body>
    <modal-footer [ERROR ->][show-default-buttons]="true"></modal-footer>
</modal>

"): ng:///AssetModule/ListassetComponent.html@90:18
'modal-footer' is not a known element:
1. If 'modal-footer' is an Angular component, then verify that it is part of this module.
2. If 'modal-footer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
        Hello World!
    </modal-body>
    [ERROR ->]<modal-footer [show-default-buttons]="true"></modal-footer>
</modal>

"): ng:///AssetModule/ListassetComponent.html@90:4
'modal' is not a known element:
1. If 'modal' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
   <button type="button" class="btn btn-default" (click)="modal.open()">Open me!</button>

[ERROR ->]<modal #modal>
    <modal-header >
        <h4 class="modal-title">I'm a modal!</h4>
"): ng:///AssetModule/ListassetComponent.html@83:0

**Comment by lafiza** [comment]
+1

**Comment by dougludlow** [comment]
Sorry for not ever getting to this. Feel free to reopen if you're still having problems.

**Comment by KeerthiYeruva** [comment]
i also getting this problem...
i have written an issue 
https://github.com/KeerthiYeruva/project/issues/1

please help me..
