### ISSUE TITLE
(index):23 Error: (SystemJS) Unexpected token < 

### ISSUE THREAD

**Issue by sayedraiyan** [dougludlow/ng2-bs3-modal#188]
Hi, i am using ng2-bs3-modal. i have configured as below
system.js
    'ng2-bs3-modal': 'npm:ng2-bs3-modal.js'

in   app.module.ts
import { Ng2Bs3ModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
@NgModule({
    imports: [BrowserModule,  BrowserAnimationsModule, ToasterModule, Ng2Bs3ModalModule],
    declarations: [AppComponent],
    providers: [],
    bootstrap: [AppComponent]
})
like this i have imported the model but i am getting some issue when i run the app, check the image below.
i am using angular 4.0.0 
and i got like this error while installing the ToasterModule at that time i have imported BrowserAnimationsModule, then that issue was resolved.

![image](https://user-images.githubusercontent.com/24208492/27737340-6b355792-5dc5-11e7-853b-de684b87017f.png)

can you please look into this issue.
thanks in advance

**Comment by dougludlow** [comment]
@sayedraiyan I recall seeing this error when my webserver was returning a 404 for the file. Check your networks tab, are you seeing any 404s?

**Comment by sayedraiyan** [comment]
@dougludlow   Issue resolved as i missed defaultJSExtensions: true, in systemjs.config. :)
