### ISSUE TITLE
Angular 4 AOT builds -- Property 'X' is private and only accessible within class 'X'.

### ISSUE THREAD

**Issue by DavidRnR** [dougludlow/ng2-bs3-modal#189]
When I try to do a build AOT, I've got this error.

# **ng2-bs4-modal**
Property 'isSmall' is private and only accessible within class 'ModalComponent'.

Property 'isLarge' is private and only accessible within class 'ModalComponent'.

How to fix it?

Go to ---->>> /node_modules/ng2-bs4-modal/src/ng2-bs4-modal/components/modal.ts

Change this function to **"public"**

![image](https://user-images.githubusercontent.com/21180828/27835630-27ed62be-60b2-11e7-981e-2b247bcca483.png)

Thanks! 

PS: Maybe we can get this feature in the next release.

**Comment by wartab** [comment]
This not the ng2-bs4-modal repository.

**Comment by DavidRnR** [comment]
Sorry wartab, I posted here because ng2-bs4-modal is a fork of this and there is a link to comments issues here.

Sorry about that.
