### ISSUE TITLE
Documentation tweak

### ISSUE THREAD

**Issue by ScottMGerstl** [dougludlow/ng2-bs3-modal#19]
In your example, you document your backdrop attribute as 

> `[backdrop]="'static'"`

If you would like, and for you information, can actually specify it through normal attribute assignment

`backdrop='static'`

Feel free to do it either way, just wanted to let you know =)

**Comment by dougludlow** [comment]
Thanks @ScottMGerstl. That's good to know!

**Comment by ScottMGerstl** [comment]
no problem, @dougludlow. I just got an implementation working; it's pretty slick. Thank you for writing it!

**Comment by dougludlow** [comment]
:thumbsup:
