### ISSUE TITLE
prod error: Property 'animation' does not exist on type 

### ISSUE THREAD

**Issue by mandelmonkey** [dougludlow/ng2-bs3-modal#191]
Hi
When I build for prod I get a lot of these types of errors, dev is fine

ERROR in ng:///Users/a/Documents/webapps/takara-dashboard/src/app/takara-options/takara-options.component.html (168,5): Property 'animation' does not exist on type 'TakaraOptionsComponent'.

ERROR in ng:///Users/a/Documen

I am running
"@angular/cli": "1.0.1",
    "@angular/compiler-cli": "^4.0.0",
"typescript": "~2.2.0"

Is there something I should be doing to stop this?

**Comment by dougludlow** [comment]
@mandelmonkey sorry for not getting to this sooner. If you're still having problems with this, feel free to reopen.

**Comment by aj92singh** [comment]
I am facing this problem. Did you find any solution for this?

**Comment by mandelmonkey** [comment]
I did but cant remember how, if it helps here is the source code where I use it
[takara-options.zip](https://github.com/dougludlow/ng2-bs3-modal/files/1669786/takara-options.zip)
