### ISSUE TITLE
Is this going to support bootstrap4?

### ISSUE THREAD

**Issue by arun-awnics** [dougludlow/ng2-bs3-modal#193]
Hi @dougludlow I have been using ng2-bs3-modal from a while now. I was using BS3 till date in my project and had to update it to BS4 now. I have been facing a few issues from the time I have upgraded my app to BS4. Is this repo going to support BS4 ever?

**Comment by pichardoJ** [comment]
@arun-awnics Im using bootstrap 4 currently and so far no issues with the modal, the only difference is the `modal-title` class which could be fixed like:

```
<modal-header>
    <h5 class="modal-title">Title</h5>
</modal-header>
```

**Comment by dougludlow** [comment]
@arun-awnics I don't have any plans to support bootstrap 4 just yet. But contributions are always welcome. In the meantime you could try using https://github.com/maxfisher05/ng2-bs4-modal.

Also, you might checkout these other libs:
https://ng-bootstrap.github.io/#/components/modal/examples
https://valor-software.com/ngx-bootstrap/#/modals
