### ISSUE TITLE
onDismiss should only be triggered if the user dismissed the modal

### ISSUE THREAD

**Issue by renehamburger** [dougludlow/ng2-bs3-modal#195]
At the moment, navigating away from a page with an modal will lead to:
- `modal.ngOnDestroy()` is called
- `modal.destroy()` is called
- `modal.hide()` is called
- Bootstrap hides the modal and triggers 'hidden.bs.modal'.
- This is converted to an emission on the observable `modal.hidden`, which in turn emits a value on `modal.onDismiss`.

Thus it is not currently possible to distinguish between the user dismissing the dialog and (possibly another action) leading to a destruction of the modal. In order to avoid a breaking change, it would be sufficient to emit a value with `onDismiss()` that signifies what triggered the dismissal.

**Comment by dougludlow** [comment]
v0.11 now emits a `BsModalCloseSource` which has `Dismiss`, `Backdrop` and `Keyboard`. We can add more sources if necessary.
