### ISSUE TITLE
Modal dialog didn't open

### ISSUE THREAD

**Issue by mariannafld** [dougludlow/ng2-bs3-modal#196]
Hello,
Demo from this repository works great on my PC.
However, when I use ModalComponent in different project (angular-cli), modal dialog is just not opening.
No exceptions are thrown.
1.
....
@ViewChild('modal') validationModal: ModalComponent;
....
validationModal object is well defined.

2.
....
this.validationModal.open();
....
Enter to open() method, in modal-instanse.ts

....
function toPromise<T>(observable: Observable<T>): Promise<T> {
    return new Promise((resolve, reject) => {
        observable.subscribe(next => {
            resolve(next);
        });
    });
}
....
resolve(next) is never reached.

Trying to be close to this demo,I added ng2-bs3-modal as a folder in the project (remove installation from node-modules). As well, I downgraded zone.js (like in demo) to 0.6.21.
These didn't lead to the solution.

Any ideas why dialog didn't open?
Thank you in advance

**Comment by ChristianBathe** [comment]
Hi,
i had the same issue and could solve it by adding bootstrap.css to the angular-cli.json:

   "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ]

Greetings
Christian

**Comment by dougludlow** [comment]
Closing for now. Feel free to reopen if you're still having problems.
