### ISSUE TITLE
Facebook share does not work

### ISSUE THREAD

**Issue by ZeroDarkThirty** [dougludlow/ng2-bs3-modal#198]
Rest of them are working fine but when I try to use Facebook share it reads: 

> Sorry, something went wrong. We're working on getting this fixed as soon as we can.

Any workaround?

**Comment by dougludlow** [comment]
@ZeroDarkThirty sorry for not getting around to this sooner. Are you still having problems with this? Can you post any code samples?

**Comment by ZeroDarkThirty** [comment]
@dougludlow Hey it's working now. Not sure what happened earlier.

**Comment by dougludlow** [comment]
👍
