### ISSUE TITLE
ng2-bs4-modal: autofocus directive overrides HTML5-autofocus

### ISSUE THREAD

**Issue by Unambiguousness** [dougludlow/ng2-bs3-modal#199]
If I use the autofocus-directive in plain html input elements outside a modal, I get the error: "No provider for ModalComponent!" This problem was already reported and fixed in ng2-bs3-modal last year with version 0.8.0 on September 9. 

But comparing the autofocus.ts files of ng2-bs3-modal and ng2-bs4-modal it's obvious that this bugfix wasn't adopted by ng2-bs4-modal.

Please apply the changes taken in ng2-bs3-modal's autofocus.ts also in ng2-bs4-modal.

**Comment by dougludlow** [comment]
@Unambiguousness ng2-bs4-modal is a fork of this project and not supported here. Sorry.

**Comment by Unambiguousness** [comment]
Well then maxfisher05 did something wrong as he referred to your project in case of issuses...
