### ISSUE TITLE
Bootstrap 3 dependency?

### ISSUE THREAD

**Issue by project707** [dougludlow/ng2-bs3-modal#2]
I assume this is required? It isn't in the package.json

**Comment by dougludlow** [comment]
@project707, it is, but perhaps it would be best to add it to peerDependencies. I don't want to lock people into a specific bootstrap package. For example, developers might want to use [bootstrap-sass](https://github.com/twbs/bootstrap-sass) over straight [bootstrap](https://github.com/twbs/bootstrap).

**Comment by project707** [comment]
Makes sense. I guess it might be worth adding some note of what it depends on and how to include/import in the readme. Closing.
