### ISSUE TITLE
update to beta 12

### ISSUE THREAD

**Issue by samvloeberghs** [dougludlow/ng2-bs3-modal#20]

**Comment by dougludlow** [comment]
When I attempted to update to beta.12 sometime last week, I got something like this error when I attempted to close the modal:

"Task does not support cancellation, or is already canceled."

This appears to be related to https://github.com/angular/angular/issues/7671. From what I understand it's actually an issue with zone.js. 

Have you not experienced a similar issue?

**Comment by dougludlow** [comment]
I guess the "Task does not support cancellation, or is already canceled." issue was solved. I'm no longer seeing it. Thanks for the pr!

**Comment by dougludlow** [comment]
Releases as v0.4.3.
