### ISSUE TITLE
Errors since latest commit

### ISSUE THREAD

**Issue by lewis-as** [dougludlow/ng2-bs3-modal#203]
Hi, 

Since the commit on the weekend we have began seeing a number of issues with our UI

- Uncaught TypeError: Cannot read property 'core' of undefined
    at BsModalCloseSource.Confirm (ng2-bs3-modal.umd.js:4)
    at ng2-bs3-modal.umd.js:5

- GET https://unpkg.com/ng2-bs3-modal@0.11.0/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal 404 ()

- Error: (SystemJS) XHR error (404) loading https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal
	Error: XHR error (404) loading https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (https://unpkg.com/zone.js@0.8.4/dist/zone.js:1393:29) [<root>]
	Error loading https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal as "ng2-bs3-modal/ng2-bs3-modal" from http://localhost:54199/app/app.module.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (https://unpkg.com/zone.js@0.8.4/dist/zone.js:1393:29) [<root>]
	Error loading https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal as "ng2-bs3-modal/ng2-bs3-modal" from http://localhost:54199/app/app.module.js

Any ideas what would have caused this or what we need to do to resolve this issue? 

We have gone through and changed ModalComponent to BsModalComponent and also Ng2Bs3ModalModule to BsModalModule as well as updating our systemjs.config.server.js file to map to https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js 

Thanks in advance
Lewis

**Comment by dougludlow** [comment]
Hi @lewis-as, v0.11.0 has a series of breaking changes that I still need to document, sorry about that. In the meantime, feel free to still use v0.10.x as a workaround.

Looking at the errors above, it's probable you just need to change the way you're referencing the package:

```typescript
import { BsModalModule } from 'ng2-bs3-modal';
```

versus:
```typescript
import { BsModalModule } from 'ng2-bs3-modal/ng2-bs3-modal';
```

**Comment by dougludlow** [comment]
@lewis-as `open` indeed doesn't exist on `BsModalModule`. Use `BsModalComponent` instead.

**Comment by dougludlow** [comment]
@lewis-as are you still running into problems with v0.11?

**Comment by lewis-as** [comment]
@dougludlow I haven't tried yet but i'm going to try again as I have a bit of an issue with opening a child modal from a parent modal. When the Child modal is closed then, focus is lost on the parent modal that launched it instead of returning focus back to it.

**Comment by dougludlow** [comment]
@lewis-as ah, I actually just fixed that issue in v0.12.

**Comment by lewis-as** [comment]
@dougludlow That's awesome, I will get this implemented

**Comment by lewis-as** [comment]
@dougludlow so current issue on this is 

Uncaught TypeError: Cannot read property 'core' of undefined
    at BsModalHideType.Close (ng2-bs3-modal.umd.js:4)
    at ng2-bs3-modal.umd.js:5

Have i missed something?

**Comment by dougludlow** [comment]
That's odd. It appears to be choking on the `global.ng.core` declaration. https://unpkg.com/ng2-bs3-modal@0.12.1/bundles/ng2-bs3-modal.umd.js.

How are you including `ng2-bs3-modal.umd.js`? Are you manually adding it as a script tag in your html?

**Comment by lewis-as** [comment]
so in the html file we have 

    <script src="../../systemjs.config.server.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
    <script src="https://unpkg.com/ng2-bs3-modal/bundles/ng2-bs3-modal.umd.js"></script>

then in the systemjs.config.server.js we have
paths: {
            'npm:': "https://unpkg.com/",
        },
map: {
            'ng2-bs3-modal': "npm:ng2-bs3-modal@0.12.1/bundles/ng2-bs3-modal.umd.js",
}

then inside the app.modal

import { BsModalModule } from "ng2-bs3-modal/ng2-bs3-modal";

@NgModule({ BsModalModule})

**Comment by dougludlow** [comment]
@lewis-as ah, ok, I think I see what's going on. If you're mapping it in your systemjs config, then you don't need to include it in your html. Also, I do include a systemjs bundle as well: `/bundles/ng2-bs3-modal.systemjs.js` that you can probably use instead.

**Comment by lewis-as** [comment]
@dougludlow Okay i think its almost there, i am now seeing this error 

localhost/:23 Error: Fetch error: 404 
localhost/:23 Error: Fetch error: 404 
  Instantiating https://unpkg.com/ng2-bs3-modal@0.12.1/bundles/ng2-bs3-modal.umd.js/ng2-bs3-modal

It seems to be trying to instantiating the url wrong and for some reason the ng2-bs3-modal is being tagged on the end. Have you experienced it before?

**Comment by dougludlow** [comment]
@lewis-as yes, import just `ng2-bs3-modal` instead of `ng2-bs3-modal/ng2-bs3-modal`, like below:

```ts
import { BsModalModule } from 'ng2-bs3-modal';
```

**Comment by lewis-as** [comment]
Hi @dougludlow current issue is this even with the change suggested
![image](https://user-images.githubusercontent.com/15770317/31273170-5efc365a-aa85-11e7-8cb4-e556377fa449.png)

this is the script from the html file

    <script src="https://unpkg.com/zone.js@0.8.4/dist/zone.js"></script>
    <script src="https://unpkg.com/systemjs@0.20.19/dist/system.src.js"></script>

    <script src="../../systemjs.config.server.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.js"></script>
 cheers

**Comment by dougludlow** [comment]
@lewis-as I'd double check that you're not importing in with the double `ng2-bs3-modal/ng2-bs3-modal` any where else in your project. That's definitely the issue and why systemjs is trying to look for it, but getting a 404. Also, try using the systemjs bundle instead of the umd bundle.

In your systemjs config replace the value you have mapped for ng2-bs3-modal to make it look something like the following:

```
...
map: {
'ng2-bs3-modal': "npm:ng2-bs3-modal@0.12.1/bundles/ng2-bs3-modal.system.js",
}
...
```

**Comment by lewis-as** [comment]
@dougludlow So I have reverted it right back to before i started making the changes and started again. 

There now seems to be an issue with compiler since making these changes. Is there a specific version that your library uses?

Console error
![image](https://user-images.githubusercontent.com/15770317/31379751-1e0a9a22-ada7-11e7-8000-75933aa0e004.png)

![image](https://user-images.githubusercontent.com/15770317/31379872-841c7236-ada7-11e7-9f2b-91fb23d7a399.png)

The error is being thrown on line 20 below

![image](https://user-images.githubusercontent.com/15770317/31379938-bd5517c4-ada7-11e7-906e-fb9449d42054.png)


Anything look a miss

**Comment by lewis-as** [comment]
@dougludlow okay found out what that issue was. The old version was still installed on the node module folder and needed to be deleted. 

Everything is running however when closing the child modal the text boxes are still disabled. 

Kind Regards

Lewis

**Comment by lewis-as** [comment]
@dougludlow sorry please see the screenshots below 

Parent modal opens in edit mode (text fields are editable)
![image](https://user-images.githubusercontent.com/15770317/31394215-b2efda7a-add5-11e7-828f-79fea93c6c82.png)

child modal opens this has disabled the background and the text fields on the parent modal
![image](https://user-images.githubusercontent.com/15770317/31394275-d516f2c8-add5-11e7-930f-edca8ab33bc4.png)

on close/dismiss of the child modal (text fields remain in disabled state)
![image](https://user-images.githubusercontent.com/15770317/31394356-007da664-add6-11e7-9672-ad5209c81ffa.png)

Other than that its all working great

--
Kind Regards
Lewis

**Comment by dougludlow** [comment]
@lewis-as the modal itself doesn't have any specific logic to disable/enable textboxes. The modal's api has changed slightly, you might make sure that your usage matches the current api as far as the close/dismiss is concerned.

**Comment by lewis-as** [comment]
@dougludlow Awesome all sorted, Thanks for all your help
