### ISSUE TITLE
Close button not dismissing the modal after upgrading to 0.11.0

### ISSUE THREAD

**Issue by jayakumarj85** [dougludlow/ng2-bs3-modal#204]
The close button is not dismissing the bs-modal. I have specified [showDismiss]="true" on the bs-modal-header and the output events are not getting emitted (onClose) & (onDismiss).

The modal is getting closed only on pressing esc key.

**Comment by dougludlow** [comment]
@jayakumarj85 looking into this now.

**Comment by darekurlik** [comment]
+1

**Comment by dougludlow** [comment]
This should be fixed in v0.11.3.

**Comment by jayakumarj85** [comment]
Thank you
