### ISSUE TITLE
no exported member 'ModalComponent'.

### ISSUE THREAD

**Issue by cmddavid** [dougludlow/ng2-bs3-modal#206]
After upgrading this package to the latest version, I keep getting this error. The module has been imported successfully, but in the component im trying to use the Modal it is still giving this error:

`ERROR in /Users/x/Documents/projects/ps-bitbucket/y/src/app/image-grid/image-grid.component.ts (2,10): Module '"/Users/x/Documents/projects/ps-bitbucket/y/node_modules/ng2-bs3-modal/ng2-bs3-modal"' has no exported member 'ModalComponent'.`

This is the way of importing:

`import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';`

Any idea what is going on?

Package versions:

>     "@angular/common": "4.4.3",
>     "@angular/compiler": "4.4.3",
>     "@angular/core": "4.4.3",
>     "@angular/forms": "4.4.3",
>     "@angular/http": "4.4.3",
>     "@angular/platform-browser": "4.4.3",
>     "@angular/platform-browser-dynamic": "4.4.3",
>     "@angular/router": "4.4.3",
>     "@angular/upgrade": "4.4.3",
>     "@ngrx/core": "^1.2.0",
>     "@ngrx/effects": "4.0.5",
>     "@ngrx/store": "^4.0.3",
>     "angular2-google-maps": "^0.17.0",
>     "bootstrap": "^3.3.7",
>     "core-js": "^2.5.1",
>     "ng2-bs3-modal": "^0.11.2",
>     "reflect-metadata": "0.1.10",
>     "rxjs": "5.4.3",
>     "ts-helpers": "^1.1.2",
>     "zone.js": "0.8.17"

**Edit: this has been solved by renaming ModalComponent to BsModalComponent in the import statement.**

**Comment by dougludlow** [comment]
@cmddavid yes, sorry I've made some breaking changes in v0.11. `ModalComponent` is now `BsModalComponent`.
