### ISSUE TITLE
Backdrop styling weirdness

### ISSUE THREAD

**Issue by dotcom9** [dougludlow/ng2-bs3-modal#210]
Using ng2-bs3-modal 0.10.4 with Angular 4.1.2, modals cause the underlying page content to be repeated and offset in the backdrop. See attached screenshot. This happens consistently throughout the application. Is a fix or workaround available for this?

![image](https://user-images.githubusercontent.com/4866561/31015272-1fac8d60-a517-11e7-94c9-1896ccfffdb5.png)

Application dependencies:

    

    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.2",
    "@angular/compiler": "^4.1.2",
    "@angular/compiler-cli": "^4.1.2",
    "@angular/core": "^4.1.2",
    "@angular/forms": "^4.1.2",
    "@angular/http": "^4.1.2",
    "@angular/platform-browser": "^4.1.2",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/platform-server": "^4.1.2",
    "@angular/router": "^4.1.2",
    "@ngtools/webpack": "^1.3.1",
    "@rds/ri-style": "^1.3.4",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.5.0",
    "es6-shim": "^0.35.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-charts": "^1.5.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-popover": "0.0.14",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.0",
    "toastr-ng2": "^4.1.1",
    "typescript-string-enums": "^0.3.4",
    "zone.js": "^0.8.10"

**Comment by dougludlow** [comment]
Yeah, that _is_ weird. I haven't seen that before. I can't do much without really knowing what your markup looks like and how you're executing the modal. Can you by chance share any of your code? 

Do you have any way to reproduce this issue outside of your application?

**Comment by dougludlow** [comment]
@dotcom9 were you able to get this figured out?

**Comment by mooziedog** [comment]
i have a same issue, too. it was appeared after update chrome. I think it was related about chrome.

**Comment by dougludlow** [comment]
Closing since there was no response. Feel free to reopen if the issue persists.
