### ISSUE TITLE
Cannot hide modal that is not fully shown

### ISSUE THREAD

**Issue by MateuszBogdan** [dougludlow/ng2-bs3-modal#212]
In some corner cases I need to hide modal before it is fully shown (like user navigates away on router).
Currently there is a huge inconsistency in handling modal closing in such case.
Look at close method:
```js
    public close(value?: any): Promise<{}> {
        this.onInternalClose$.next(BsModalHideType.Close);
        return this.hide()
            .do(() => this.onClose.emit(value))
            .toPromise()
            .then(() => value);
    }
```

At first everything seems ok but then look at hide method:
```js
    private hide(): Observable<BsModalHideType> {
        if (!this.visible) return Observable.of<BsModalHideType>(null);

        return Observable.create((o: Observer<any>) => {
            this.onHidden$.take(1).subscribe(next => {
                o.next(next);
                o.complete();
            });

            this.$modal.modal('hide');
        });
    }
```

In my corner case this.visible is still false (since modal is not fully shown yet). So this code will fire `onInternalClose$` then emit `onClose` (without even calling `this.$modal('hide')`).

What is really the point of this line?
```js
if (!this.visible) return Observable.of<BsModalHideType>(null);
```

**Comment by dougludlow** [comment]
@MateuszBogdan, the point of the line above is to allow close to resolve a promise if the modal is not open. I'm open to any better solutions. I'll try playing around with your particular edge case and see what I can come up with.

**Comment by dougludlow** [comment]
@MateuszBogdan I believe I've got a solution for this. Try out v0.13 and let me know if that works for you.

**Comment by MateuszBogdan** [comment]
@dougludlow v0.13 is working like a charm. Thank you.

**Comment by dougludlow** [comment]
No problem!
