### ISSUE TITLE
Scroll issues when using two modals

### ISSUE THREAD

**Issue by kzrfaisal** [dougludlow/ng2-bs3-modal#213]
Scroll issue is coming when opening a model( model2 ) from another model(model1),
model1  height is greater than screen size so it requires scrolling, which is working fine unless model2 is opened from a link given in model1.

**Comment by dougludlow** [comment]
Hey @kzrfaisal, what version of ng2-bs3-modal are you using? Are you seeing issues scrolling in the first modal or the second one?

**Comment by dougludlow** [comment]
Closing since there was no response. Feel free to reopen if the issue still exists.
