### ISSUE TITLE
fsevents

### ISSUE THREAD

**Issue by dloukola** [dougludlow/ng2-bs3-modal#22]
It looks like you depend on a package "fsevents@1.0.8". Unfortunately this only is supported on MacOsX. Is this an important dependency? I'd like to try an use your project on Windows.

**Comment by samvloeberghs** [comment]
got the same error!

**Comment by dougludlow** [comment]
Hey @dloukola, @samvloeberghs,

`fsevents` is a dependency of karma, which I use for testing. On Windows, it typically throws a warning about an *optional* dependency (fsevents) that failed to install, however this is a warning and karma will work regardless. See https://github.com/karma-runner/karma/issues/1609.

Karma is one of the devDependencies, so you shouldn't see this error if you install via npm. If you are cloning the repo, running `npm install --production` will not install devDependencies. But ng2-bs3-bootstrap actually doesn't have any dependencies aside from peerDependencies and those are not installed by npm anymore.
