### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by AHelper** [dougludlow/ng2-bs3-modal#220]
Angular 5 was released nearly a month ago.  Could this get updated to support it?  This should probably come as a major version bump in this module.

Thanks!

**Comment by dougludlow** [comment]
@AHelper thanks for opening this. What is ng2-bs3-modal lacking in order to support Angular 5? As far as I know, it should "just work".

**Comment by AHelper** [comment]
Ah, yes, I was scanning through our dependencies again and picked up on the ^4.0.0 **dev**Dependencies rather than the >=2.0.0 peerDependencies here. Sorry for the false alarm!
