### ISSUE TITLE
focus coming out of Modal after pressing Tab key

### ISSUE THREAD

**Issue by sripalreddyadamala** [dougludlow/ng2-bs3-modal#236]
Hi,

I am using ng2-bs3-modal@^0.13.0  modal component in one of our projects.

Our requirement is to trap the focus inside the modal however the focus is moving outside of the modal on tabbing. It then stays outside the modal until it traverses all the tabs on the page.

Is there a way you could keep the focus trapped inside the modal until the modal is closed? Or in other words it should continue looping with focus being within the modal.

Expected behavior – Focus should be trapped inside the modal window and on closing it focus should move to the element which triggers the modal window.

This is critical interaction for AX users. Appreciate any support you can provide with regards to this.
![image](https://user-images.githubusercontent.com/17653691/37886864-0f06cd4e-308c-11e8-9177-7d3cd122c93a.png)

**Comment by dougludlow** [comment]
@sripalreddyadamala were you able to find a solution?

**Comment by sripalreddyadamala** [comment]
Actually no I am still working and I dont have a solution for it. I am
actually using your modal in 10 places in my application and we are making
our website with ADA complaince and I do not have a solution for it.

Thanks & Regards,
Sripal Adamala
sripalui@gmail.com
8315780693
