### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by JuanAlejandroRosalesCoronel** [dougludlow/ng2-bs3-modal#240]
Hi,

Is it possible to have an Angular 6 based build?

Thanks in advance,

**Comment by emostafa** [comment]
I would like that too because i am upgrading my projects and currently ng2-bs3-modal is breaking my builds because it doesn't play nicely with rxjs 6.0.0.

**Comment by elixiao** [comment]
add rxjs polyfill in your angular6 project could fix related build problem:

```sh
yarn add rxjs-compat
# npm install rxjs-compat
```

**Comment by SergejSachs** [comment]
thats only a temporary solution because this package will be deprecated in Angular 7

**Comment by jarcik** [comment]
@SergejSa and this information can be found where, please? Or from what information you assume?

**Comment by JBeater** [comment]
Hi how it look. I want to remove rxjs-compat as soon as possible but bs3-modal is still incompatible.
Do you want help with update?

**Comment by emostafa** [comment]
Chech my pull request, its two month old
https://github.com/dougludlow/ng2-bs3-modal/pull/241

**Comment by JBeater** [comment]
After update is there issue, when i try run though ng serve compiler cannot find ng2-bs3-modal, it try to find it in whole project but unsuccess.

Log looks like:

> Module not found: Error: Can't resolve 'ng2-bs3-modal/ng2-bs3-modal' in 'D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\app\assets-manager\asset-layout'
> resolve 'ng2-bs3-modal/ng2-bs3-modal' in 'D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\app\assets-manager\asset-layout'
>   Parsed request is a module
>   using description file: D:\Analityca Design\Zoomfab\zoomfabMain\webApp\package.json (relative path: ./src/app/assets-manager/asset-layout)
>     Field 'browser' doesn't contain a valid alias configuration
>     resolve as module
>       looking for modules in D:/Analityca Design/Zoomfab/zoomfabMain/webApp/src
>         using description file: D:\Analityca Design\Zoomfab\zoomfabMain\webApp\package.json (relative path: ./src)
>           Field 'browser' doesn't contain a valid alias configuration
>           using description file: D:\Analityca Design\Zoomfab\zoomfabMain\webApp\package.json (relative path: ./src/ng2-bs3-modal/ng2-bs3-modal)
>             no extension
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\ng2-bs3-modal\ng2-bs3-modal doesn't exist
>             .ts
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\ng2-bs3-modal\ng2-bs3-modal.ts doesn't exist
>             .mjs
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\ng2-bs3-modal\ng2-bs3-modal.mjs doesn't exist
>             .js
>               Field 'browser' doesn't contain a valid alias configuration
>               D:\Analityca Design\Zoomfab\zoomfabMain\webApp\src\ng2-bs3-modal\ng2-bs3-modal.js doesn't exist
>             as directory

**Comment by dougludlow** [comment]
@JBeater try importing from just `ng2-bs3-modal` instead of `ng2-bs3-modal/ng2-bs3-modal`. 

The build changed a little bit...

**Comment by JBeater** [comment]
@dougludlow thanks, it work fine 👍
