### ISSUE TITLE
ERROR TypeError: this.$modal.modal is not a function

### ISSUE THREAD

**Issue by ranjik2909** [dougludlow/ng2-bs3-modal#244]
Angular 5.2.11
ng2-bs3-modal version 0.13.0

I am trying to update angular version from 4.0 to 5.2. But ng2-bs3-modal is not working for me.  Following is the error I am seeing in the console. 

![ng2-bs3-modal error](https://user-images.githubusercontent.com/28634958/41745015-cf62af7a-7562-11e8-8c12-0d83d3762e3f.PNG)

I previously used version 0.12.1 with angular 4.0. I did not have this issue then. 

Note: The error I am seeing is after I put the following in app.module.ts

import * as $ from 'jquery';
window["$"] = $;
window["jQuery"] = $;

Before this the error was 'jQuery is not defined'

![image](https://user-images.githubusercontent.com/28634958/41745538-7baaa5ac-7564-11e8-84d2-ba67526276d7.png)

I am using angular-cli. Following is the order of scripts loaded in angular.json file (angular-cli.json in angular 4.0)

"scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/bootstrap/js/modal.js",
              "node_modules/ng2-bs3-modal/ng2-bs3-modal.js"
]

I appreciate any help. Thanks.

**Comment by dougludlow** [comment]
Try removing `jquery` and `bootstrap` from your scripts and then do the following:

Add a file called `jquery.ts` and copy in the following:
```
import * as $ from 'jquery';
window["jQuery"] = window["$"] = $
```

Then in your `app.module.ts` add the following to the top of the file:
```
import './jquery';
import 'bootstrap/js/modal';
```

**Comment by dougludlow** [comment]
Checkout the demo's [`main.ts`](https://github.com/dougludlow/ng2-bs3-modal/blob/master/src/main.ts#L1-L2) for an example.
