### ISSUE TITLE
Unable to install "npm install --save ng2-bs3-modal"

### ISSUE THREAD

**Issue by shankarAtjunglee** [dougludlow/ng2-bs3-modal#25]
while trying to installing i am getting this error
`32028 error Windows_NT 6.1.7601
32029 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "ng2-bs3-modal"
32030 error node v4.4.0
32031 error npm  v2.14.20
32032 error code EBADPLATFORM
32033 error notsup Unsupported
32033 error notsup Not compatible with your operating system or architecture: fsevents@1.0.8
32033 error notsup Valid OS:    darwin
32033 error notsup Valid Arch:  any
32033 error notsup Actual OS:   win32
32033 error notsup Actual Arch: ia32
32034 verbose exit [ 1, true ]
32035 verbose unbuild node_modules\ng2-bs3-modal
32036 info preuninstall ng2-bs3-modal@0.4.3
32037 info uninstall ng2-bs3-modal@0.4.3
32038 verbose unbuild rmStuff ng2-bs3-modal@0.4.3 from E:\wsJs\h5\popups\node_modules
32039 info postuninstall ng2-bs3-modal@0.4.3`

********************
While using -f install works. But run time exception is there.

**Comment by dougludlow** [comment]
@shankarAtjunglee what version of npm are you running?

**Comment by shankarAtjunglee** [comment]
@dougludlow  2.14.20

**Comment by dougludlow** [comment]
Ah, I've only tested with v4 and v5. From the error, fsevents is a dependency of karma, which is a dev dependency of ng2-bs3-modal, and *shouldn't* be installed. This appears to be an issue with npm.

**Comment by dougludlow** [comment]
I found this issue, but it looks like it's for v3: https://github.com/npm/npm/issues/11039

**Comment by dougludlow** [comment]
Found this issue as well. I shrink wrapped my packaged and it appears that npm2 is trying to install everything in the shrink wrap: https://github.com/npm/npm/issues/8707

**Comment by dougludlow** [comment]
This one as well: https://github.com/npm/npm/issues/2679

**Comment by dougludlow** [comment]
@shankarAtjunglee I've removed my shrinkwrap file and published a new release. Try version 0.4.4 and let me know how that goes.

**Comment by slavasitnikov** [comment]
@dougludlow last version in npm is still 0.4.3

**Comment by shankarAtjunglee** [comment]
@dougludlow 
problem is still same. here is what i did
1. Created new Folder(test)
2. Created new Fresh package.json
3. run command "npm install --save ng2-bs3-modal"
4. still same error.
************
other details
1. OS windows7
2. Npm -v = 2.14.20
************
npm-debug.log
`32011 verbose pkgid fsevents@1.0.8
32012 verbose cwd E:\wsJs\h5\test
32013 error Windows_NT 6.1.7601
32014 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "ng2-bs3-modal"
32015 error node v4.4.0
32016 error npm  v2.14.20
32017 error code EBADPLATFORM
32018 error notsup Unsupported
32018 error notsup Not compatible with your operating system or architecture: fsevents@1.0.8
32018 error notsup Valid OS:    darwin
32018 error notsup Valid Arch:  any
32018 error notsup Actual OS:   win32
32018 error notsup Actual Arch: ia32
32019 verbose exit [ 1, true ]
32020 verbose unbuild node_modules\ng2-bs3-modal
32021 info preuninstall ng2-bs3-modal@0.4.3
32022 info uninstall ng2-bs3-modal@0.4.3
32023 verbose unbuild rmStuff ng2-bs3-modal@0.4.3 from E:\wsJs\h5\test\node_modules
32024 info postuninstall ng2-bs3-modal@0.4.3`

**Comment by dougludlow** [comment]
Sorry, I guess I forgot to publish... :tired_face: It should be there now.
