### ISSUE TITLE
Is there any way to set focus for a button on your dialog after opening it?

### ISSUE THREAD

**Issue by dougludlow** [dougludlow/ng2-bs3-modal#26]
From Fuit Attila:
Is there any way to set focus for a button on your dialog after opening it?

**Comment by dougludlow** [comment]
Let me take a look at it this evening.

One idea is to create an [attribute directive](https://angular.io/docs/ts/latest/guide/attribute-directives.html), that [OnInit](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hooks-overview) sets focus on the element it's attached to, specifically a textbox.

**Comment by dougludlow** [comment]
Fuit Attila: I added an "autofocus" directive that you can add to any element you want to autofocus on when the modal is opened. I've updated the documentation with an example. Feel free to checkout v0.4.7 and let me know how it goes.

**Comment by fuitattila** [comment]
Cool it works perfectly! Thank you for your quick help!
