### ISSUE TITLE
The second time the modal is dismissed with the keyboard or backdrop the onDismiss event is not being fired

### ISSUE THREAD

**Issue by okoleilat** [dougludlow/ng2-bs3-modal#27]

**Comment by dougludlow** [comment]
Thanks for reporting this. Taking a look now.

**Comment by okoleilat** [comment]
Actually, the onDismissed is being called always for the first action if it is a close or dismiss.

Thank you :)

**Comment by dougludlow** [comment]
@okoleilat this should be fixed in v0.4.6. Try it out and let me know how it goes.

**Comment by okoleilat** [comment]
perfect :) It is indeed fixed. Keep up the good work 👍
