### ISSUE TITLE
Add id value into modal-dialog.

### ISSUE THREAD

**Issue by duinzaghi** [dougludlow/ng2-bs3-modal#29]
I'm using your package to show modal-dialog. I want to custom width of modal-dialog. Currently we only can set width by add size value(sm or lg). Can you add id value (defined in "modal" selector) into the root div like this: 
`<div` class="modal-dialog" [ngClass]="{ 'modal-sm': isSmall(), 'modal-lg': isLarge() }" id="your-custom-id">`
I think with id value we can custom style for modal-dialog easily.
Please help me to solve this issue. Thanks.

**Comment by dougludlow** [comment]
@duinzaghi sure, it would probably make sense to transfer the class attribute to the modal as well. I can probably take a look into that tonight.

**Comment by dougludlow** [comment]
@duinzaghi I've released v0.5.0, where you should be able to set the id and/or class on a modal without issue. Let me know how it goes.
