### ISSUE TITLE
Resize issue if using a custom component in modal-body

### ISSUE THREAD

**Issue by amaurymartiny** [dougludlow/ng2-bs3-modal#30]
Hello,

I'm creating on my page a modal, and in the body of it I put a custom component ```mail-template-form```
```.
        <modal (onClose)="closed()" #modal>
            <modal-header [show-close]="true">
                <h4 class="modal-title">Envoyer le devis</h4>
            </modal-header>
            <modal-body>
                <mail-template-form showSubmit="false" [mailTemplate]="mailTemplate" #mtf></mail-template-form>
            </modal-body>
            <modal-footer>
                <button (click)="modal.dismiss()" class="btn btn-default">Fermer</button>
                <button (click)="modal.close()" class="btn btn-success">Envoyer</button>
            </modal-footer>
        </modal>
```

When rendered, the modal-body's div height is 0, which causes a bad display of the modal footer's buttons.
![captura de pantalla 2016-04-07 a las 09 10 46](https://cloud.githubusercontent.com/assets/1293565/14343397/e95dfc8c-fca0-11e5-9a79-8e8fd9106f1c.png)

**Comment by dougludlow** [comment]
Interesting. I can probably take a look at that this evening. Can you provide the rendered markup of the mail-template-form component?

**Comment by dougludlow** [comment]
@amaurymartiny the only way I was able to repro this is when I'm floating the form fields. I was able to fix that by adding the bootstrap `clearfix` class to the `modal-body`. You might try that and see if it resolves the issue.

```html
<modal (onClose)="closed()" #modal>
    <modal-header [show-close]="true">
        <h4 class="modal-title">Envoyer le devis</h4>
    </modal-header>
    <modal-body class="clearfix">
        <mail-template-form showSubmit="false" [mailTemplate]="mailTemplate" #mtf></mail-template-form>
    </modal-body>
    <modal-footer>
        <button (click)="modal.dismiss()" class="btn btn-default">Fermer</button>
        <button (click)="modal.close()" class="btn btn-success">Envoyer</button>
    </modal-footer>
</modal>
```

**Comment by dougludlow** [comment]
@amaurymartiny did that solve your issue?

**Comment by dougludlow** [comment]
Feel free to reopen if you're still having issues.
