### ISSUE TITLE
 this.$modal.modal is not a function

### ISSUE THREAD

**Issue by nilsigusi** [dougludlow/ng2-bs3-modal#34]
Hi, by opening modal I am getting:

```
TypeError: this.$modal.modal is not a function
    at ModalInstance.show (modal-instance.ts:49)
```

what could it be?

**Comment by nilsigusi** [comment]
here my dependancies:

```
"dependencies": {
    "angular2": "2.0.0-beta.9",
    "bootstrap": "^3.3.6",
    "es6-promise": "^3.1.2",
    "es6-shim": "^0.33.3",
    "font-awesome": "^4.5.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "^5.0.0-beta.2",
    "systemjs": "^0.19.24",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0",
    "typescript": "^1.8.2"
  }
```

**Comment by dougludlow** [comment]
@nilsigusi could you provide a code sample?

**Comment by Diluka** [comment]
I have encounter the same problem. But I solved it that I forgot the script tag in `index.html`. 
Just like this will be alright:
```
    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="node_modules/ng2-bs3-modal/bundles/ng2-bs3-modal.js"></script>
```

**Comment by dougludlow** [comment]
Closing due to no response. Feel free to open again if you're still seeing issues.

**Comment by StephenLujan** [comment]
I am experiencing this same issue with scripts loaded in the same order as Diluka.

**Comment by dougludlow** [comment]
Can you post your html?

**Comment by StephenLujan** [comment]
Sorry. There was a bit of duplication going on. I had jQuery both loaded on the page directly, and imported into a typescript application with system js. Removing the import and system js setup for jQuery solves the issue, but leaves error spam about '$' in the tsc build and IDE even though it works at run-time. Just need to figure out a way to make system JS import jQuery first. It sounds like similar issues may occur with bootstrap.js without using this package so the problem is a bit out of scope I think.

**Comment by Ankita-Jaiswal** [comment]
Install jquery and bootstrap in your project 

npm install jquery
npm install bootstrap

then import both in the file (for eg model-view.component.ts) where you are using this modal
import 'jquery';
import 'bootstrap';

For me this worked flawlessly :)

**Comment by nguni52** [comment]
@Ankita-Jaiswal That helped me immensely! Thanks. :-)

**Comment by wartab** [comment]
@StephenLujan I recommend installing @types/jquery to avoid those warnings.
