### ISSUE TITLE
Unhandled Promise rejection on calling modal from component

### ISSUE THREAD

**Issue by bhambanip** [dougludlow/ng2-bs3-modal#35]
Getting 
Unhandled Promise rejection: No provider for ModalComponent! (AutofocusDirective -> ModalComponent) ; Zone: angular ; Task: Promise.then ; Value: 

on calling modal from component

**Comment by dougludlow** [comment]
@bhambanip strange, can you provide a code sample? How are you calling the modal?

**Comment by dougludlow** [comment]
Are you using tha autofocus directive within the modal component?

**Comment by dougludlow** [comment]
Closing due to no response. Please reopen if you're still seeing issues.
