### ISSUE TITLE
TypeError: require is not a function

### ISSUE THREAD

**Issue by theunreal** [dougludlow/ng2-bs3-modal#36]
```
rror: TypeError: require is not a function
	    at eval (http://localhost:3000/node_modules/ng2-bs3-modal/ng2-bs3-modal.js:5:15)
	    at eval (http://localhost:3000/node_modules/ng2-bs3-modal/ng2-bs3-modal.js:23:3)
	    at ZoneDelegate.invoke (http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:332:29)
	Evaluating http://localhost:3000/node_modules/ng2-bs3-modal/ng2-bs3-modal.js
	Error loading http://localhost:3000/node_modules/ng2-bs3-modal/ng2-bs3-modal.js as "ng2-bs3-modal/ng2-bs3-modal" from http://localhost:3000/app/main-menu.component.js
```

when putting the MODAL_DIRECTIVES

**Comment by dougludlow** [comment]
@theunreal are you using SystemJS to load your scripts?  You need to map it in your config or add a script reference to the bundle.

**Comment by dougludlow** [comment]
Closing due to no reponse. Feel free to open if the issue persists.

**Comment by vvh-empora** [comment]
same problem here

**Comment by vvh-empora** [comment]
<script>
        System.config({
            map: {
                'ng2-bs3-modal': '/admin-outfit-flow/node_modules/ng2-bs3-modal'
            }
        });
    </script>

**Comment by dougludlow** [comment]
@vvh-empora you might check out the [SystemJS example project](https://github.com/dougludlow/ng2-bs3-modal-demo-systemjs), and see how your setup compares. What version of SystemJS are you using?

**Comment by vvh-empora** [comment]
hmmm... my `systemjs` version ist "0.19.25" but i have fix the problem by include the source file directly:

`import {MODAL_DIRECTIVES} from "ng2-bs3-modal/src/ng2-bs3-modal/ng2-bs3-modal";`

do you know this case?

**Comment by dougludlow** [comment]
@vvh-empora sorry for not responding for a while, things have been busy. Yes, that would make sense if the `System.config` doesn't have the [`defaultJSExtensions`](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions) flag set, or an entry to the packages doesn't exist for ng2-bs3-modal, that sets the `defaultExtension` property to `js`.

**Comment by valmassoi** [comment]
adding `System.defaultJSExtensions = true;` to system.config.js fixed it for me. thanks @dougludlow
