### ISSUE TITLE
Input parameters orther than a boolean is ignored

### ISSUE THREAD

**Issue by FunksMaName** [dougludlow/ng2-bs3-modal#4]
In modal-footer.ts, I added 
` @Input('action-button-text') actionButtonText: string= "Save";`

Within the template, I added 
`<button type="button" class="btn btn-info" (click)="modal.close()" [hidden]="!showDefaultButtons">{{actionButtonText}}</button>`

And Finally, within the modal itself, i added
` <modal-footer  [action-button-text]="Delete" [show-default-buttons]="true"></modal-footer>`

This just shows a blank button, instead of a button with the text "Delete". Changing the input parameter to a boolean works Or actually passing in a boolean value from the modal template. Any ideas :) ?

**Comment by dougludlow** [comment]
@FunksMaName I added your code to [this plunk](https://plnkr.co/edit/mjkTdg?p=preview) and figured out what was going on. You need to surround the value in the `[action-button-text]` attribute with quotes, like so:

    <modal-footer [action-button-text]="'Delete'" [show-default-buttons]="true"></modal-footer>

The intent was that if you wanted to customize the modal-footer, you could simply add your own markup, like so:

    <modal-footer>
        <button type="button" class="btn btn-default" (click)="modal.dismiss()">Close</button>
        <button type="button" class="btn btn-primary" (click)="modal.close()">Delete</button>
    </modal-footer>

I should document that.

However, I just discovered a bug with regards to styling where the default buttons are not hidden as the `hidden` style angular provides is being overridden by the `btn` style. I've just fixed that.

**Comment by FunksMaName** [comment]
Wonderful, markup in the footer template is definitely the way to go. Also great to know what my issue was for when I need to work with input parameters on my project. Thanks

**Comment by dougludlow** [comment]
@FunksMaName: :thumbsup:
