### ISSUE TITLE
Close event when selected outside of modal

### ISSUE THREAD

**Issue by chrismcgregor** [dougludlow/ng2-bs3-modal#41]
Is there an event I can capture when someone selects outside of the modal and it closes?

**Comment by dougludlow** [comment]
@chrismcgregor yes, onDismiss is emitted when the backdrop is clicked and the modal is hidden.

**Comment by chrismcgregor** [comment]
Excellent, thank you!
--
Christopher McGregor
415.624.6261 // chris@mcgregor.io
