### ISSUE TITLE
Closing with header [x] does not emit onClose event

### ISSUE THREAD

**Issue by fuitattila** [dougludlow/ng2-bs3-modal#43]
I think in your ModalComponent you should also emit onClose.
`
dismiss(): Promise<void> {
        return this.instance.dismiss();
    }
`
Can you insert this feature?

**Comment by dougludlow** [comment]
@fuitattila onDismiss should be emitted when the `x` is clicked. Is this not the case?

**Comment by fuitattila** [comment]
@dougludlow onDismiss is that event what I am looking for. Sorry for false issue:)

**Comment by dougludlow** [comment]
No worries 😀
