### ISSUE TITLE
Support Angular 2.0.0-rc.1

### ISSUE THREAD

**Issue by fuitattila** [dougludlow/ng2-bs3-modal#44]
Dear Doug!

Can you please upgrade your module to support  Angular 2.0.0-rc.1?

Current problem - now Angular is on a different path:
`node_modules/ng2-bs3-modal/ng2-bs3-modal.d.ts(1,22): error TS2307: Cannot find module 'angular2/core'.`

More info here:
`https://github.com/angular/angular/blob/master/CHANGELOG.md`

And if you have any ngFor loops at your module, you shoud change the `#` to `let`. Tha was a breaking change in beta.17.

Thank you for your help!

**Comment by born2net** [comment]
be great if we can push to rc.1

**Comment by atmsharif** [comment]
Hi @born2net 
I found couple of issues/bugs after the Rc1 upgrade.
In RC1 ngOnDestroy can be called even when $modal is null, it's causing the router/app to break.
I forked and put a fix for this. Are you ok for me to merge the changes to your code base?

Cheers,
Sharif

**Comment by born2net** [comment]
of course...

**Comment by amaurymartiny** [comment]
@born2net Any reason why you are not doing a PR?

**Comment by born2net** [comment]
I did do one, but not sure how the author wants to handle my package.json as I had to modify it to work in Windows (diff from original)

**Comment by dougludlow** [comment]
Let me take a look at the pr and get it merged in. Thanks @born2net!

**Comment by dougludlow** [comment]
v0.6.0 is compatible with angular 2.0.0-rc.1. Thanks @born2net.
