### ISSUE TITLE
onClose emit undefined

### ISSUE THREAD

**Issue by loganfreeman** [dougludlow/ng2-bs3-modal#49]
```js
    close(): Promise<void> {
        return this.instance.close().then(() => {
            this.onClose.emit(undefined);
        });
    }
```

why onClose emit undefined? how to get the ModalResult?

**Comment by dougludlow** [comment]
`onClose` emits when the modal is closed. `onDismiss` emits when the modal is dismissed.

**Comment by dougludlow** [comment]
In earlier versions I used to emit the ModalResult, but I found I didn't need to if I had two separate event emitters.
