### ISSUE TITLE
Undefined when using modal.open()/modal.close() in parent component

### ISSUE THREAD

**Issue by MagnusKnalstad** [dougludlow/ng2-bs3-modal#50]
Hi, I am working on a production application, and throughout the project had problems using for instance "this.modal.open() " in the component.ts file. 

Console gives
browser_adapter.ts:78 ORIGINAL EXCEPTION: TypeError: Cannot read property 'open' of undefined.

The strange thing is that in one of the components, which has several instances of the modal component, one of them works. The other modals will give the error explained above. So only one of the modal-objects in one component file is working. 

For some of the modals-objects,  it is fine just to use the method inside the html-file. This works perfectly.
But now we have come to a point where we need one of the modals to be triggered in the parent.ts component. 

We are using the modal in several components as well where it is only one modal-instace in the html file, but we will get the same error. Followed your examples correclty and tried to copy it to see if we have done something wrong, but it just will give the same error.

All imports are included and directives are used correctly. Triple checked several times, and I have got to the conclusion that it is time to make an issue, as I just cannot figure out what is wrong or if this is a common issue?

Thanks

**Comment by dougludlow** [comment]
@MagnusKnalstad thanks for reporting the issue. Is it possible to share any of your code?

**Comment by MagnusKnalstad** [comment]
Sure! 
Can use an example of this Mail Component.
This is wanted to be triggered from NgOnInit LifeCycle when the component is called on.
![mailcomp](https://cloud.githubusercontent.com/assets/12196221/15330262/6708de10-1c5c-11e6-8662-09ebd4752060.jpg) when enabling <email></email> selector to become true.

Workaround temporary have been to make a transparecy-button inside in the html button above as you can see under here, which then became visible in the other component where the email-selector is beeing used. That is not a good way to do it.

![mailhtml](https://cloud.githubusercontent.com/assets/12196221/15330450/2cb262b2-1c5d-11e6-84bb-34ac92b1bf06.jpg)

**Comment by dougludlow** [comment]
Okay, I think I know what's going on here. `ngOnInit` is too early, the child views haven't been initialized yet. Try `ngAfterViewInit` instead. See [Component lifecycle Hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#hooks-overview) from the Angular2 docs for more details. 

From the docs:

> `ngAfterViewinit`: After Angular creates the component's view(s).

**Comment by MagnusKnalstad** [comment]
There we go! As for the other components, I think its the same red thread here as well. They use two way binding [(NgModel)], and they are objects that are being initilized in NgOnInit.

example: 

testobject : Object

ngOnInit(){

testobject = new Object();
}


onChange(valid){
if(valid)
    this.modal.open(); //Gives undefined
}
 Some of them have a (change)-method that triggers for validation, that when true, the modal opens. So i think the same problem accures here, that the modal is already set to undefined in then ngOnInit, maybe, For this case I made another solution so that the modal opens first and gives the validation instead of popping up when valid. 

Anyway, this solved my issue, and thanks for super fast response!
Magnus

**Comment by dougludlow** [comment]
Great! Glad I could help!

**Comment by umesh190690** [comment]
same problem is still getting

**Comment by umesh190690** [comment]
```
import {Component,OnInit,ViewChild} from "@angular/core";
import {ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';

@Component({
    selector:'<dash></dash>',
     templateUrl:"../../dist/app/template/Dashboard/home.template.html",
     styleUrls: ['../../dist/app/template/Dashboard/home.style.css']
})
export class DashComponent {

        modal:ModalComponent;
        constructor(private translate: TranslateService){
        }
      //modal
    @ViewChild('modal')
    close(){
        this.modal.close();
    }
    opens(){
     this.modal.open();
     console.log("Open"); 
   }
}
```

html is 
```

<button type="button" class="btn btn-default" (click)="opens()">Open me!</button>

<modal #modal>
    <modal-header [show-close]="true">
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    <modal-body>
        Hello World!
    </modal-body>
    <modal-footer [show-default-buttons]="true">
      <button (click)="close()">Close</button>
    </modal-footer>
</modal>
```

**Comment by umesh190690** [comment]
got the Solution :) 

```
 //modal:ModalComponent //old Error
 @ViewChild('modal')
    modal:ModalComponent; //new  ! solved
    close(){
      this.modal.close();
    }
    opens(){
      this.check=true;
      if(this.check){
          this.modal.open();
          console.log("Open"); 
       }
    }
}
```

need to instantiate after decorator

**Comment by bob1457** [comment]
I encountered this issue when I tried to close/dismiss the modal. (I am using angular cli)
I have a component of product-ezq.components, the modal is in the html:
<modal #modal1>
   <form (ngSubmit)="onSubmit()">
      <input>....
      <button type="submit"></button>
     <button (click)="resetForm()" type="cancel" data-dismiss="modal" >Cancel</button>
   </form>
</modal>, 
(a form is inside the modal)

What I need to do is when clicking the submit button, a http request to RESTFul will be made, on success, it will close the modal, My code in product-ezq.component.ts:

import {  ViewChild, ViewChildren, Component, OnInit, AfterViewInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';

import { ProductService } from '../../shared/services/index';

@Component({
  selector: 'app-product-ezq',
  templateUrl: './product-ezq.component.html',
  styleUrls: ['./product-ezq.component.scss']
})
export class ProductEzqComponent implements AfterViewInit {

@ViewChild('modal1 ')
modal: ModalComponent;
  msg: string;


requestForm = new FormGroup({
    orgName: new FormControl('', Validators.required),
    ....
      country: new FormControl()
    })
  });
  constructor(private productService:ProductService) { }

  ngOnInit() {
  }

  ngAfterViewInit() {
    // available here
  }

onSubmit(){
    console.log(this.requestForm.value); // Testing only

    // use service to send http request to post form data
    this.msg = '';


    this.productService.SendRequest(this.requestForm.value)//;
    .subscribe(data => {if (data === 1) //Success
            {
              this.msg = 'Data successfully updated.';
              //this.LoadUsers();
            }
            // tslint:disable-next-line:one-line
            else {
              this.msg = 'There is some issue in saving records, please contact to system administrator!';
            }      
      this.modal.dismiss();
    },
      error => {}
    )}

  resetForm(){
    this.requestForm.reset();
  }
}

When I tested by clicking submit button, I got error saying: 
ERROR TypeError: Cannot read property 'dismiss' of undefined,

What I am missing here? 

I have jquery.js and  bootstrap.js using cdn in the index.html. Ng2Bs3ModalModule was loaded and imported in app.module.ts.

I read almost all I can find on this issue, but no luck.

Please help.

**Comment by bob1457** [comment]
I also tried to create a separate component for the form, just load it inside <modal></modal>, and in this component ts file, implement onSubmit function to make a http call and close the modal. Here, not child view, right, just inside the modal component to try to close it. The same error, "dismiss not defined". I guess it might be I did not load the library properly?
