### ISSUE TITLE
TypeError: this.$modal.modal is not a function

### ISSUE THREAD

**Issue by guzmo** [dougludlow/ng2-bs3-modal#52]
I keep getting 

> TypeError: this.$modal.modal is not a function

when I click a button to open a modal with this.modal.open().

I've tried to find the error but can't figure it out. 
When I am inspecting this.$modal.modal(); in modal-instance.js:37 it looks like this.

> 0:modal.modal.fade
> context:modal.modal.fade
> length:1

Which feels wrong but I dunno. :P

My dependencies are:
  ```
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.1",
    "bootstrap-sass": "^3.3.6",
    "core-js": "^2.3.0",
    "es6-shim": "^0.35.0",
    "jquery": "^2.2.3",
    "ng2-bootstrap": "^1.0.13",
    "ng2-bs3-modal": "^0.6.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "systemjs": "0.19.25",
    "zone.js": "^0.6.12"
```

Would appreciate any help (Y)

**Comment by dougludlow** [comment]
This could be happening if jquery of bootstrap haven't been loaded yet. How are you loading your dependencies?

**Comment by guzmo** [comment]
I have a main.ts file that bootstraps everything.

```
bootstrap(
    AppComponent,
    [
        ROUTER_BINDINGS, 
        HTTP_PROVIDERS,
        provide(BrowserXhr, {useClass:CORSBrowserXhr})
    ]); 
```
Im loading the scripts with 

```
<script src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
<script src="bundle.js"></script>
```

and thats about it.

In my @Component I'm importing 

```
import { MODAL_DIRECTIVES, ModalComponent  } from 'ng2-bs3-modal/ng2-bs3-modal';
```

and trying to reach the model with ( where I have #modal in my html )

```
@ViewChild('modal')
modal: ModalComponent;
```

Triggering this.modal.open(); when I click a button.

**Comment by dougludlow** [comment]
How are you generating your bundle.js? I suspect the script for bootstrap is not being loaded or is not being loaded in the right order.

**Comment by guzmo** [comment]
Gulp + webpack 

```
return gulp.src(config.app + 'app/main.ts')
        .pipe(webpack(require('./webpack.config.js')))
        .pipe(gulp.dest(config.dist));
```

By bootstrap you mean bootstrap 3.x js file? or do you mean how I am bootstrapping it? :P

The only bootstrap script I'm loading is ng2-bootstrap.

**Comment by guzmo** [comment]
Installed bootstrap and import 'bootstrap'; and everything works fine now.

Thanks for the assistance.

**Comment by eRez-ebs** [comment]
@guzmo  - can you please explain how did you installed and imported bootstrap?
my dependencies already includes `"bootstrap": "^3.3.6"` yet i'm still facing the exact same problem.

**Comment by LPalmito** [comment]
+1 @eRez-ebs, same issue for me!
Though unlike @guzmo I'm using only `webpack` (and not `gulp`), and the `<modal>` notation instead of `@ViewChild`. Here are more precisions:

- I've got also:
```
ORIGINAL EXCEPTION: TypeError: this.$modal.modal is not a function
```

- I've properly installed `boostrap` in my `package.json`:
```
    "bootstrap": "^3.3.6",
```

- my `component.ts`
```
import {MODAL_DIRECTIVES} from "ng2-bs3-modal/ng2-bs3-modal";
@Component({
    selector: 'my-component',
    moduleId: module.id,
    template: require('./template.html'),
    directives: [
        MODAL_DIRECTIVES,
        CORE_DIRECTIVES]
})
```

- my `template.html`:
```
<div class="btn btn-primary modify-button" (click)="widgetModal.open()">
    Open modal
</div>

<modal #widgetModal (onOpen)="onOpen()" (onClose)="onClose()">
    <modal-header>
        <h1>Modal's title</h1>
    </modal-header>
    <modal-body>
        Modal's body
   </modal-body>
</modal>
```

What could I be missing here?

**Comment by guzmo** [comment]
I can take a look at it but not before sunday am I afraid. Im on the way to border a boat and no computer ( vacation yay ) :P

**Comment by eRez-ebs** [comment]
@LPalmito  - ok, with the help of a colleague i've figured it out.
after installing bootstrap `npm install bootstrap --save` which didn't do the job, i've added to the project's index.html `<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>` (which i copied from [here](http://getbootstrap.com/getting-started/#download)).
once doing that i got an error `bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3` - apparently i was using jQuery 3.0.0, so took jQuery 1.9.1 from here`https://blog.jquery.com/2013/02/04/jquery-1-9-1-released/`, replaced it with the version i was using and voila - the modal was opened!

**Comment by dougludlow** [comment]
@LPalmito I don't use webpack, but it may have something to do with the order that it's including the files. `ng2-bs3-modal` really depends on both jquery and bootstrap, so they need to be loaded and availabel globally in order for `ng2-bs3-modal` to use them.

**Comment by LPalmito** [comment]
That was it @dougludlow and @eRez-ebs, thanks a lot for your detailed explanation! :)

**Comment by winni4eva** [comment]
this helped me solve this problem http://stackoverflow.com/questions/37840333/how-to-add-bootstrap-3-to-angular2-webpack-based-project

**Comment by alexkaskasoli** [comment]
I'm getting the same error, using systemjs. Are you guys using ng2-bootstrap?

I'm loading bootstrap and jquery before systemjs:
```
<html>
  <head>
    <base href="/">
    <title>Vision Web UI</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="static/css/app.css" rel="stylesheet">

    <!-- 1. Load libraries -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="node_modules/ng2-bootstrap/bundles/ng2-bootstrap.min.js"></script>
    
    <!-- 2. Configure SystemJS -->
    <script src="static/js/systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>
  </head>
  <!-- 3. Display the application -->
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```
In my systemjs config I have:
`'ng2-bs3-modal':              'npm:ng2-bs3-modal',`

I'm using the `default modal` example, and when I click on the button I get:
`this.$modal.modal is not a function`

**Comment by alexkaskasoli** [comment]
So I dropped `ng2-bootstrap`, it was giving me a fair deal of trouble. I'm now loading my jquery, bootstrap css and bootstrap js directly, in this order:

```
    <!-- CSS -->
    <link href="node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    ...

    <!-- 1. Load libraries -->
    ...
    <script src="node_modules/jquery/dist/jquery.min.js"></script>
    <script src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
```
And still in my SystemJS config:
`'ng2-bs3-modal':              'npm:ng2-bs3-modal'`

The README examples work fine now.

**Comment by mhawila** [comment]
In my case I didn't have boostrap js loaded

**Comment by Ankita-Jaiswal** [comment]
Install jquery and bootstrap in your project

npm install jquery
npm install bootstrap

then import both in the file (for eg model-view.component.ts) where you are using this modal
import 'jquery';
import 'bootstrap';

For me this worked flawlessly :)

**Comment by AkshatSrivastava2** [comment]
@Ankita-Jaiswal Thanks alot.. Worked for me.
