### ISSUE TITLE
Cannot read property 'open' of undefined

### ISSUE THREAD

**Issue by vknaveenkumar** [dougludlow/ng2-bs3-modal#56]
Cannot read property 'open' of undefined

**Comment by dougludlow** [comment]
@vknaveenkumar thanks for reporting this. Could you provide some more detail and perhaps a code sample?

**Comment by dougludlow** [comment]
Also, please take a look at #50 and #54 and see if any of those details assist you.

**Comment by vknaveenkumar** [comment]
i cant get it. can u please help me in solving this . At what time would u come ? (IndianStandardTime)

**Comment by dougludlow** [comment]
@vknaveenkumar I'm sorry, but without more detail I can't be of much help.

**Comment by dougludlow** [comment]
Yes, the example from the readme should suffice:

### Opening and closing the modal from a parent component
```typescript
import { Component, ViewChild } from '@angular/core';
import { MODAL_DIRECTIVES, ModalComponent } from 'ng2-bs3-modal/ng2-bs3-modal';

@Component({
    selector: 'parent-component',
    directives: [MODAL_DIRECTIVES],
    template: `
        <modal #myModal>
            ...
        </modal>
    `
})
export class ParentComponent {
    @ViewChild('myModal')
    modal: ModalComponent;

    close() {
        this.modal.close();
    }

    open() {
        this.modal.open();
    }
}
```

**Comment by dougludlow** [comment]
Also, take a look at the working demo code: https://github.com/dougludlow/ng2-bs3-modal/tree/master/demo

**Comment by saurav12** [comment]
@dougludlow The above example you've given is not working. I am unable to import 
```
{ MODAL_DIRECTIVES } from 'ng2-bs3-modal/ng2-bs3-modal';
```

What is the problem here. I've also looked at the demo example you've given but it doesn't give any example like we need & you've stated above. Please help!

**Comment by dougludlow** [comment]
@saurav12 that example is old/outdated, please refer to the example in the readme:                     https://github.com/dougludlow/ng2-bs3-modal#opening-and-closing-the-modal-from-a-parent-component

If you are getting "Cannot read property 'open' of undefined" that is because you haven't loaded bootstrap properly. ng3-bs3-modal relies on bootstrap's javascript in order to work.
