### ISSUE TITLE
TypeError: self.context.opened is not a function

### ISSUE THREAD

**Issue by ajayambre** [dougludlow/ng2-bs3-modal#58]
I want a modal dialog that has a form with several input fields using <code>[(ngModel)]</code> whose values I want to fetch and pre-fill the form and then save the values if user updates them.

I am trying to open a modal dialog from my component by doing
<code>this.modal.open()</code>

The modal dialog opens but I get this error in the console and Angular2's data binding and change detection stops working after that for my component:
![image](https://cloud.githubusercontent.com/assets/5074211/15679786/bc192602-2770-11e6-9394-aead9ce29da5.png)

**Comment by dougludlow** [comment]
@ajayambre could you possibly post your component's code, including the template? My hunch is that you are referencing a callback in the template that doesn't exist, but I could be completely off.

**Comment by ajayambre** [comment]
@dougludlow I tried to reproduce my case here [Grid Modal Demo](http://plnkr.co/edit/Kv9LSiNgMElZ8Sll142j?p=preview)

But now I am getting this error
![image](https://cloud.githubusercontent.com/assets/5074211/15699592/b517d1fc-27eb-11e6-997d-df83b1f9187d.png)

I am not sure if I am missing something here.
Thanks.

**Comment by ajayambre** [comment]
@dougludlow Thanks. You were right. 
I had this in my template <code>\<modal #mymodal (onOpen)="opened()"></code> but I forgot to add <code>opened()</code> in my component. Sorry for that.

**Comment by ajayambre** [comment]
@dougludlow I tried to reproduce my case here [Grid Modal Demo](http://plnkr.co/edit/Kv9LSiNgMElZ8Sll142j?p=preview)

But now I am getting this error
![image](https://cloud.githubusercontent.com/assets/5074211/15699592/b517d1fc-27eb-11e6-997d-df83b1f9187d.png)

I am not sure if I am missing something here.
Thanks.

**Comment by dougludlow** [comment]
Yup, you're just missing the bootstrap.js and bootstrap.css. http://plnkr.co/edit/pB1gbAK9LUgwN6AM3isC

```html
<link rel="stylesheet" href="http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.css">
<script src="http://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.js"></script>
```
