### ISSUE TITLE
Dynamic modal body content

### ISSUE THREAD

**Issue by fgauer** [dougludlow/ng2-bs3-modal#59]
Hi,

I would like to do something like this:

    <modal-body>
        Delete This Thing: {{somethingToDelete}}?
    </modal-body>

...and have model.open() plug in the contents of {{somethingToDelete}} dynamically. Right now, since modal-body is brought in when model.init() is called, {{somethingToDelete}} gets set to some value at init() time and does not change.

For instance if I have a list of things a user could delete, I would like to pass in some information from that list and have the modal display what they are actually deleting, instead of just a static message.

Is there some way to have {{ }}'s rendered and built at modal.open() time?

Thanks in advance!

**Comment by dougludlow** [comment]
@fgauer sorry for not responding sooner, this is already possible. You don't need to pass anything into modal.open(), you simply change the value of `somethingToDelete` prior to opening it.

**Comment by fgauer** [comment]
Thanks Doug! I will give it a try again. I was having trouble getting it to work but it could certainly be something I'm doing. Much appreciated!

**Comment by dougludlow** [comment]
Let me know how it goes.
