### ISSUE TITLE
onClose not firing

### ISSUE THREAD

**Issue by taguan** [dougludlow/ng2-bs3-modal#61]
Hello,

I noticed that the "onClose" EventEmitter only fires when we explicitly call the close method. This is not very useful, I would have expected the event to be also fired when the modal is closed by clicking the X or outside of the modal, or when hitting Esc, ...

**Comment by dougludlow** [comment]
@taguan, in those cases onDismiss is emitted.

**Comment by taguan** [comment]
Sorry, I just found the onDismiss event doing exactly that.
I still feel the onClose is a bit misleading and that is cumbersome to have to listen to two different events when we want to now when the modal is closed by any way.

Shouldn't at least onDismiss be fired when we close the modal ?

But ok for closing that issue
