### ISSUE TITLE
memory leak: modal elements pollute the body

### ISSUE THREAD

**Issue by sgbeal** [dougludlow/ng2-bs3-modal#62]
i'm seeing the following: when switching back and forth between views which use modals, their `<modal>` parts are being recreated on each visit and stuffed into the DOM, and their old DOM elements are still in the body. i've added this to all affected components:

```
ngOnDestroy(){
    if(this.modal){
        this.modal.close();
    }
}
```

but that's not solving it - the DOM elements are still left lying around. We _desperately_ need a way of cleaning those up.

This is easy to test: switch back and forth between views which use their own modal and run this in the console on each visit:

```
  $('modal').length
```

**Comment by sgbeal** [comment]
Adding this to my ngOnDestroy():

     $('modal').remove()

is only partially working - some views are doing it and others not (which would seem to imply an A2 event-firing bug).

BTW: this is angular2 RC1 and modal 0.6.1.

**Comment by sgbeal** [comment]
The current workaround seems to be to add this to many different components:

    ngOnInit(){
        Workarounds.cleanupModals();
    }

and...

     export const Workarounds = {
        /**
         *  workaround for https://github.com/dougludlow/ng2-bs3-modal/issues/62
         *  Force removal of all MODAL tags in the body element.
         *
         *  In theory this belongs in the ngOnDestroy(), but that is not being called consistently!
         *  However, placing it in ngOnInit() of all elements with Modals seems to work (with a minor caveat
         *  involving visits where a subcomponent holding a modal is never initialized, but no big deal).
         */
        cleanupModals: function(){
            $('body modal').remove();
            return this;
        }
    };


The good news is that the Modal component recreates the DOM elements as needed, so this _seems_ to have no nasty side-effects.

**Comment by sgbeal** [comment]
i have looked through the bs3 code and as far as i can see, it is trying to clean up the DOM elements via ngOnDestroy() (by way of ModalInstance::destroy()), so my suspicion at the moment is that ngOnDestroy() is not being called (as mentioned in a previous comment), meaning that this might actually be an angular2 bug.

**Comment by dougludlow** [comment]
@sgbeal thanks for looking at this. I'm a little swamped at the moment, but I'll trying to look into it soon.

**Comment by dougludlow** [comment]
@sgbeal what router are you using?

**Comment by sgbeal** [comment]
The RC1 one (not router-deprecated). In fact, i looked into hooking into that to clean up the extra instances, because it supposedly has lifetime hooks, but the docs for them are completely empty :(.

**Comment by sgbeal** [comment]
Specifically:

https://angular.io/docs/ts/latest/guide/router.html#!#router-lifecycle-hooks

is currently empty, but in theory one could hook in there to destroy `<modal>` when changing views.

**Comment by dougludlow** [comment]
Yeah... they did have docs on the RC router for a little while, but now they're gone. Which version of the RC router? I noticed recently that 3.0.0-aplha.3 is the latest and they moved it to a new repo (https://github.com/angular/vladivostok), but it seemed to be missing a lot of features.

**Comment by sgbeal** [comment]
BTW: i managed to work around it by simply nuking all `<modal>` tags via `ngOnInit()` in all views which use this module (we've got 8 or 10 such views). This was a dirty hack, but it works with (surprisingly) no noticeable side effects. It leaves us with, at most, one stray `<modal>` in the page body, but it's invisible and isn't bothering anyone. i only accidentally noticed the behaviour this morning (we've been using bs3 since a few days after A2RC1 came out... early May?).

**Comment by sgbeal** [comment]
i have no idea which version of the router - whatever they bundle in `@angular/router` rc1. i can check the version tomorrow at work.

**Comment by sgbeal** [comment]
`@angular/router/package.json` simply says 2.0.0-rc.1:

`https://registry.npmjs.org/@angular/router/-/router-2.0.0-rc.1.tgz`

**Comment by sgbeal** [comment]
correction: removing the DOM elements as i demonstrate above DOES have a bad side effect: onClose/Dismiss listeners are removed, and we need those to cancel timers running in the modal view. Eeek. Calling empty() instead of remove() leads to an invisible modal.

**Comment by dougludlow** [comment]
This should be solved.
