### ISSUE TITLE
missing onDismiss emit in dismiss()

### ISSUE THREAD

**Issue by sgbeal** [dougludlow/ng2-bs3-modal#63]
from modal.ts:

    close(): Promise<void> {
        return this.instance.close().then(() => {
            this.onClose.emit(undefined);
        });
    }

    dismiss(): Promise<void> {
        return this.instance.dismiss();
    }

dismiss needs to send an event as well, IMO. (i am trying to work around #62 and am hoping that manually connecting listeners will avoid side efects of forcibly removing the DOM element.)

i think dismiss() needs to be:

    dismiss(): Promise<void> {
        return this.instance.dismiss().then(() => {
            this.onDismiss.emit(undefined);
        });
    }

**Comment by dougludlow** [comment]
@sgbeal `onDismiss` should be emitted here: https://github.com/dougludlow/ng2-bs3-modal/blob/master/src/ng2-bs3-modal/components/modal.ts#L45

This should emit not only when `dismiss` is called explicitly, but also when the modal is dismissed via keyboard and by clicking on the backdrop.

**Comment by sgbeal** [comment]
Fair enough - i didn't specifically notice any broken behaviour, just the inconsistency compared to the close() impl.
