### ISSUE TITLE
modal allignment

### ISSUE THREAD

**Issue by vknaveenkumar** [dougludlow/ng2-bs3-modal#64]
My modal is displaying at the top of the page instead center .Is there is any solution?

**Comment by samvloeberghs** [comment]
you could adapt the css of bootstrap to show it somewhere else.

**Comment by kalbond** [comment]
That would require a change in the template. Is there a solution that doesn't involve template change?

**Comment by kalbond** [comment]
Found a workaround. For those interested:
**CSS:**
```
.modal{
    display: table;
    height: 100%;
    width: 45%;
    margin: 0 auto;
}
.modal-dialog{
    display: table-cell;
    vertical-align: middle;
}
```

**Template:**
```
<modal *ngIf = "showModal" #accessModal>..... </modal>
<a (click)="openModal()">Some Link</a>
```

**Component:**
```
openModal(){
    this.showModal = true;
    setTimeout(()=>{
      this.modal.open();   
    },10);
  }
```

**Comment by dougludlow** [comment]
Thanks @kalbond. @vknaveenkumar feel free to search something like "bootstrap modal center vertically" if @kalbond's solution doesn't work for you, I'm sure there are many ways to do it. Here's another one: http://stackoverflow.com/questions/18053408/vertically-centering-bootstrap-modal-window. 

Another interesting way to do it would be to use flexbox.
