### ISSUE TITLE
Multiple model in single page 

### ISSUE THREAD

**Issue by vijay21soni** [dougludlow/ng2-bs3-modal#66]
how can i use multiple model in single page?
for Ex. : 
![untitled](https://cloud.githubusercontent.com/assets/6205138/16262638/17b72864-388e-11e6-8fbd-4a57b0856e20.png)

**Comment by fuitattila** [comment]
Dear @vijay21soni!

If you want to control both of your modal from a component controller you should have 2 @ViewChild decorator, like that:

```javascript
@ViewChild('Modal1') modal1:ModalComponent;
@ViewChild('Modal2') modal2:ModalComponent;
```
Now you can handle your modals from component after **ngAfterViewInit*** hook like that:
```javascript
this.modal1.open();
this.modal2.open();
```

*You wrote Model not Modal - as you can see.*

*F:Y.I.:https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html

**Comment by vijay21soni** [comment]
Thanks for reply,
it is working.
it is a great toll but you have to update according to angular 2 currnet
 release.



Sincerely,
Vijay Soni
sky id: vijaysoni.net
mobile: +91-9067635885

**Comment by Methodician** [comment]
Thanks. My problem was I was doing this:

```
@ViewChild('Modal1')
@ViewChild('Modal2')
modal1: ModalComponent;
modal2: ModalComponent;
```
Which seemed close enough to the code examples. Might want to adjust the examples to show them on the same line to avoid confusion going forward.

**Comment by dougludlow** [comment]
@Methodician ha ha, yeah you'll want to annotate the correct property. :)

@vijay21soni glad it's working for you now.

@fuitattila thanks for your help!
