### ISSUE TITLE
escape key

### ISSUE THREAD

**Issue by fripp0971** [dougludlow/ng2-bs3-modal#7]
Apparently if you leave the tabindex="-1" off the div, the escape key wont close the modal automatically.

Any chance you could add an input for the modal to not close on escape which sets that tabindex?

Thanks!

Love the modal otherwise!

**Comment by dougludlow** [comment]
[v0.1.5](https://github.com/dougludlow/ng2-bs3-modal/releases/tag/v0.1.5) adds support for the [keyboard option](http://getbootstrap.com/javascript/#modals-options). You can now set `[keyboard]="false"`. See the following example:
```
<button type="button" class="btn btn-default" (click)="modal.open()">Open me!</button>

<modal #modal [keyboard]="false" [backdrop]="'static'">
    <modal-header [show-close]="false">
        <h4 class="modal-title">I'm a modal!</h4>
    </modal-header>
    <modal-body>
        Hello World!
    </modal-body>
    <modal-footer [show-default-buttons]="true"></modal-footer>
</modal>
```

Thanks to @Beardles for the submission.

**Comment by fripp0971** [comment]
Thanks for adding this. So I take it I was the second one to ask for this?

**Comment by dougludlow** [comment]
Apparently so :smile:

**Comment by fripp0971** [comment]
Works great. Thanks again.
