### ISSUE TITLE
Nested modals: second modal's backdrop under first modal

### ISSUE THREAD

**Issue by lmcarreiro** [dougludlow/ng2-bs3-modal#73]
When I open a second modal that is smaller than the first one, it's backdrop is apearing under the first modal.
I think it should appear over it, there are some examples:
http://jsfiddle.net/CxdUQ/
http://miles-by-motorcycle.com/static/bootstrap-modal/index.html

I get these examples from http://stackoverflow.com/questions/19305821/multiple-modals-overlay

**Comment by dougludlow** [comment]
Hmm... sounds like we need to be a little smarter with the CSS on stacked modals. Pull requests welcome here.

**Comment by fuitattila** [comment]
@dougludlow will you fix this, or you wait for help? The app we made, opens modals not in correct z-index order. If a modal was sooner added to DOM, that will be behind of the newer modal.

**Comment by sverma16** [comment]
Any plans to fix this?

**Comment by diegoRodriguezAguila** [comment]
I have the same problem, but using <md-select> inside the modal. I think it would be great to have the chance to set the modal's z-index manually. Doing some tests, setting the z-index:2 for the modal and z-index:1 for the overlay makes the md-select be shown properly over the modal

**Comment by MehranJanfeshan** [comment]
Any update on this? @dougludlow

**Comment by kalew8** [comment]
For those still struggling with this, the fix in the StackOverflow post above works perfectly well.

https://stackoverflow.com/questions/19305821/multiple-modals-overlay

**Comment by dougludlow** [comment]
This should be solved in v0.11.
