### ISSUE TITLE
customer button how to work?

### ISSUE THREAD

**Issue by ruanzy** [dougludlow/ng2-bs3-modal#74]
customer button how to work?

**Comment by samvloeberghs** [comment]
what's a customer button?

**Comment by ruanzy** [comment]
$(body).append('<button (click)="f()">click</button>');

the button click not work?

**Comment by ruanzy** [comment]
$(body).append(`<button (click)="f()">click</button>`);

the button click not work?

**Comment by dougludlow** [comment]
@ruanzy I'm sorry, but it's not exactly clear what you are asking. The code you have pasted in is jQuery and not exactly angular2 or ng2-bs3-modal related...

**Comment by naoufelus** [comment]
Thx dougludlow 

make a small example plunk for RC version https://embed.plnkr.co/aY8QLL9nOldpDS4Mk5pt/

**Comment by dougludlow** [comment]
@naoufelus cool, looks like it's working great. @ruanzy does that help?
