### ISSUE TITLE
unable to run the npm-demo

### ISSUE THREAD

**Issue by eRez-ebs** [dougludlow/ng2-bs3-modal#75]
Hi,
i've cloned the ng2-bs3-modal-demo-npm, ran `npm install` which went fine, and then `npm run build` which fails. 
made sure i have latest npm (3.10.5) and node (4.4.7), yet still i'm getting:
`> ng2-bs3-modal-demo-npm@1.0.0 build C:\Users\ehuberman\Documents\projects\Github\test\ng2-bs3-modal-test\ng2-bs3-modal
> typings install && tsc -p .

'typings' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ru
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! ng2-bs3-modal-demo-npm@1.0.0 build: `typings install && tsc -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-bs3-modal-demo-npm@1.0.0 build script 'typings install && tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bs3-modal-demo-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-bs3-modal-demo-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-bs3-modal-demo-npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ehuberman\Documents\projects\Github\test\ng2-bs3-modal-test\ng2-bs3-modal-demo-npm\npm-debug.log`

using win7.
will appreciate any help.
cheers,
eRez

**Comment by samvloeberghs** [comment]
You should install typings as the error clearly states:
```
'typings' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by eRez-ebs** [comment]
@samvloeberghs  - thanks for your reply.
installed 'typings', and now (after running `npm run build`) i get this:
`> ng2-bs3-modal-demo-npm@1.0.0 build C:\Users\ehuberman\Documents\projects\Github\test\ng2-bs3-modal-test\ng2-bs3-modal-demo-npm
> typings install && tsc -p .


└── (No dependencies)

node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/compiler.d.ts(13,59): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(9,58): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/component_resolver.d.ts(13,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(61,148): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(102,144): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(107,139): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(81,90): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(85,99): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(89,99): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal-instance.d.ts(16,13): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal-instance.d.ts(17,14): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal-instance.d.ts(18,16): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal-instance.d.ts(19,16): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal.d.ts(19,20): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal.d.ts(21,26): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal.d.ts(22,14): error TS2304: Cannot find name 'Promise'.
node_modules/ng2-bs3-modal/components/modal.d.ts(23,16): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! ng2-bs3-modal-demo-npm@1.0.0 build: `typings install && tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ng2-bs3-modal-demo-npm@1.0.0 build script 'typings install && tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-bs3-modal-demo-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-bs3-modal-demo-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-bs3-modal-demo-npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ehuberman\Documents\projects\Github\test\ng2-bs3-modal-test\ng2-bs3-modal-demo-npm\npm-debug.log`

where do i go from here?
btw - i get the same error if i run `typings install && tsc -p .`
cheers!

**Comment by eRez-ebs** [comment]
i found [this](https://github.com/angular/quickstart/issues/63), and used the answer of puvaasam which resolved my problem.  i'm now able to `run build` without errors, but now i'm puzzled as to how do i make this project actually run?  there's not 'start' script.
how do i actually test it?

**Comment by dougludlow** [comment]
@eRez-ebs simple loading the index.html in a browser should work. Typically I use a small static webserver like [node-static](https://github.com/cloudhead/node-static) to serve up the files.

**Comment by dougludlow** [comment]
@eRez-ebs are you still having issues getting the demo running?

**Comment by eRez-ebs** [comment]
thanks, but i gave up after succeeding running the real thing
