### ISSUE TITLE
Leverage the onClose EventEmitter by sending parameters

### ISSUE THREAD

**Issue by mattes42** [dougludlow/ng2-bs3-modal#76]
Assumed I have two buttons that do not dismiss, but close the modal. Both buttons return different values that the component that opened the modal can react to. That would be easy when the `close EventEmitter` would accept parameters instead of `undefined`.  Find a proposal below:

 
```
  close(data:any): Promise<void> {
        return this.instance.close().then(() => {
            this.onClose.emit(data);
        });
    }
```

**Comment by dougludlow** [comment]
Sure, I can see the issue if there are multiple close buttons on the modal and you want to differentiate between them. Feel free to make a pull request.

**Comment by dougludlow** [comment]
@mattes42 this should work now in v0.8.1.
