### ISSUE TITLE
custom size

### ISSUE THREAD

**Issue by eRez-ebs** [dougludlow/ng2-bs3-modal#79]
Hi,
i have 2 different modals, both are small.  however, i want one of them to be 350px wide.
if i add this to my local css file - 
`@media (min-width: 768px) {
  .modal-sm {
    width: 350px;
  }
}`

both of them become 350px wide.
i tried using the example [here](https://coolestguidesontheplanet.com/bootstrap/modal.php), by adding `#enableProducModal`  right before `.modal-sm` but it had no affect.
is there any way to set a custom size for each modal seperately?

cheers,
eRez

**Comment by guichengwu** [comment]
I have the same problem. How to customize the size of modal dialog?

**Comment by dougludlow** [comment]
Due to #65, you should be able to solve this in the latest version, v0.7.0, by adding a custom css class to your modal. Something like the following should work:

```css
.my-modal {
    width: 250px;
}
```

```html
<modal [cssClass]="'my-modal'"></modal>
```

See the [demo source](https://github.com/dougludlow/ng2-bs3-modal/blob/master/demo/modal-demo.component.html#L38) for more detail.

**Comment by eRez-ebs** [comment]
thanks for providing the solution, but i'm unable to update to v0.7.0.
i remove the ng2-bs3-modal library from the node_modules library root, and the relevant line from the dependencies in package.json of my project, and then either run `npm install --save ng2-bs3-modal` or simply `npm update` but eventually i'm left with v0.6.1 and when i add the `[cssClass]` property i get an exception `Can't bind to 'cssClass' since it isn't a known native property`

??

**Comment by dougludlow** [comment]
@eRez-ebs hmm... perhaps 0.6.1 is the latest supported for the version of angular you have installed?

**Comment by eRez-ebs** [comment]
i'm using version 2.0.0-rc.4, which - AFAIK - is the latest
[https://angular.io/docs/ts/latest/guide/npm-packages.html](url)
