### ISSUE TITLE
onClose reset form values

### ISSUE THREAD

**Issue by AJMalik007** [dougludlow/ng2-bs3-modal#80]
I am trying to reset the form value when close button click. How to do this?

**Comment by dougludlow** [comment]
I guess it depends on how your form is setup, but in theory you should be able to do this by subscribing the onClose or onDismiss event emitters and then performing your logic in there.

**Comment by dougludlow** [comment]
@AJMalik007 you ever get this figured out? Feel free to reopen if not.

**Comment by rcmedeiros** [comment]
I don't know if there's an official way but I found this:
`
<modal (onClose)="handleClose()" #myModal>
			<form #myForm="ngForm">`
...
`@ViewChild('myForm') public myForm: NgForm;`
...
`  handleClose() {`
`// do my things`
 `this.myForm.reset();`
`  }`

**Comment by wartab** [comment]
@rcmedeiros That's perfectly valid.
