### ISSUE TITLE
Error when trying to open modal

### ISSUE THREAD

**Issue by estradamarkie** [dougludlow/ng2-bs3-modal#81]
I'm getting an error when I try to execute the open function, I've installed the module and followed the instruction how to install it in my application.

Error:
` TypeError: self._el_312.open is not a function`

Btn:
`<button (click)="modal.open()">Self-checkout</button>`

systemconfig
```
<script>
       System.config({
          defaultJSExtensions: true,
          map: {
              'ng2-bs3-modal': 'node_modules/ng2-bs3-modal'
          }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>
```

**Comment by dougludlow** [comment]
@estradamarkie feel free to share your fix...

**Comment by tareq89** [comment]
Hey @estradamarkie, did you find any fix? I am facing the same problem!

**Comment by estradamarkie** [comment]
Hi yeah I just forgot to inject the module as a directive in my component. That's why the modal wasn't opening.

**Comment by tareq89** [comment]
Haha, looks like I have been doing the same mistake all along! Thanks :)

**Comment by estradamarkie** [comment]
haha yeah it was a small step but annoying.
