### ISSUE TITLE
onDismiss is fired only half of the time

### ISSUE THREAD

**Issue by LPalmito** [dougludlow/ng2-bs3-modal#84]
Hey!

It's exactly the issue [#27](https://github.com/dougludlow/ng2-bs3-modal/issues/27) which I'm having, but on version 0.7.0. Is it possible that going to RC caused that bug to appear again somehow, or am I missing something on my side?

Thanks!

**Comment by dougludlow** [comment]
Strange, I have tests in place that look for that specific issue...

**Comment by LPalmito** [comment]
Hum OK, I have a clue for you after doing some tests. it's related to the `show-default-buttons` attribute in the `modal-footer`:
- when it's set to `false` (or keep it `false` by default) I'm having this issue
- if I set it to `true`, everything is working properly.

I hope it'll help you!

**Comment by dougludlow** [comment]
@LPalmito interesting, I'll try to take a look over the next few days.

**Comment by dougludlow** [comment]
@LPalmito - I'm unable to repro this at all. Are you still noticing thie behavior?

**Comment by dougludlow** [comment]
Feel free to reopen if it comes up again.
