### ISSUE TITLE
Open modal form component directly

### ISSUE THREAD

**Issue by engmkurd** [dougludlow/ng2-bs3-modal#85]
How to open a modal form component, once the component initialized (ex: startup guide)

**Comment by dougludlow** [comment]
@engmkurd - take a look at the example in the readme: https://github.com/dougludlow/ng2-bs3-modal#opening-and-closing-the-modal-from-a-parent-component

**Comment by dougludlow** [comment]
@engmkurd were you able to get this figured out? Feel free to reopen if not.
