### ISSUE TITLE
npm install issue on Windows 10

### ISSUE THREAD

**Issue by thardes2** [dougludlow/ng2-bs3-modal#86]
I executed the "Building" steps in your readme. The command 

> npm install

gave me an error. The overall message was as follows:

> src/ng2-bs3-modal/components/modal-footer.ts[16, 65]: " should be '
> src/ng2-bs3-modal/components/modal-footer.ts[17, 61]: " should be '

When I changed to according lines in your code, the installation worked out.
Old:
```
export class ModalFooterComponent {
    @Input('show-default-buttons') showDefaultButtons: boolean = false;
    @Input('dismiss-button-label') dismissButtonLabel: string = "Dismiss";
    @Input('close-button-label') closeButtonLabel: string = "Close";
    constructor(private modal: ModalComponent) { }
}
```
New:
```
export class ModalFooterComponent {
    @Input('show-default-buttons') showDefaultButtons: boolean = false;
    @Input('dismiss-button-label') dismissButtonLabel: string = 'Dismiss';
    @Input('close-button-label') closeButtonLabel: string = 'Close';
    constructor(private modal: ModalComponent) { }
}

```

**Comment by dougludlow** [comment]
@thardes2, sorry it took so long, but this should be fixed in v0.8.0.
