### ISSUE TITLE
RC5

### ISSUE THREAD

**Issue by damiandennis** [dougludlow/ng2-bs3-modal#91]
You probably are already aware of the breaking changes in RC5 with modules. Any chance we can can a module made for these components.

**Comment by chambersDon** [comment]
Same problem here.  Can we get an update on when a new version will be ready?

**Comment by maxfisher05** [comment]
I've updated the bootstrap 4 fork to use RC5 with modules: https://github.com/maxfisher05/ng2-bs4-modal/commit/968bc9c2c54a0b700985fb2d25b1b9b836ac0725 
I don't think this commit could be directly merged back from fork but changes should be pretty similar.

**Comment by jcannata** [comment]
I worked around this problem by creating a shared module like so...

`import { NgModule }           from '@angular/core';`
`import { CommonModule }       from '@angular/common';`
`import { MODAL_DIRECTIVES } from 'ng2-bs3-modal/ng2-bs3-modal';`

`@NgModule({
  imports: [ CommonModule ],
  declarations: [ MODAL_DIRECTIVES ],
  exports: [ MODAL_DIRECTIVES, CommonModule  ]
})
export class SharedModule { }`

Then I imported this module in AppModule (and any other module dependent on ng2-bs3-modal).
You may then remove any directives : [MODAL_DIRECTIVES] statements in those components that rely on ng2-bs3-modal.

**Comment by AHelper** [comment]
Note that with RC6 just being released, there are changes that break the current ng2-bs3-modal.

**Comment by damiandennis** [comment]
@AHelper whats the breaking change, my wrapper module seems to still work after the upgrade?

**Comment by wartab** [comment]
Angular removed directives, in essence.

**Comment by dougludlow** [comment]
Should be good to go in v0.8.0.
