### ISSUE TITLE
Issue with autofocus directive

### ISSUE THREAD

**Issue by adaneam** [dougludlow/ng2-bs3-modal#92]
Seems like the "autofocus" directive that comes with ng2-bs3-modal overrides the default autofocus attribute. If you assign autofocus to an input element which is not a part of a modal dialog, you get "No provider for ModalComponent!" exception.

**Comment by dougludlow** [comment]
@adaneam this is hopefully fixed in v0.8.0. Lemme know if you find otherwise.
