### ISSUE TITLE
Test Failures with Angular rc6

### ISSUE THREAD

**Issue by jamiewastin** [dougludlow/ng2-bs3-modal#98]
The NPM dependencies on angular will match against the latest rc version, i.e.

    "@angular/common": "^2.0.0-rc.4",

Therefore, ng2-bs3-modal is now pulling in rc6, which is causing the tests to fail:

    02 09 2016 09:06:25.024:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket     
    02 09 2016 09:06:25.212:WARN [web-server]: 404: /base/node_modules/@angular/core/testing.js
        PhantomJS 2.1.1 (Linux 0.0.0) ERROR LOG: 'Unhandled Promise rejection:', '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@angular/core/testing.js
        Error loading http://localhost:9876/base/node_modules/@angular/core/testing.js', '; Zone:', '<root>', ';  Task:', 'Promise.then', '; Value:', Error{stack: null, originalErr: Error{}, line: 796, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?cd4b6c7a76d4c40c011394993459bd07ed77bb86'}, null

This has caused the tests to fail on master, and any incoming pull requests. There are no notes in the Angular rc6 release notes that refer to this as a breaking change, needs further investigation.

**Comment by dougludlow** [comment]
@jamiewastin tests should be fixed in v0.8.0.
