### ISSUE TITLE
RC6 Error: Generic type 'Type<T>' requires 1 type argument(s) 

### ISSUE THREAD

**Issue by curlyfro** [dougludlow/ng2-bs3-modal#99]
v.0.7.0

this error is in:

\node_modules\ng2-bs3-modal\ng2-bs3-modal.d.ts

**Comment by lhammond** [comment]
+1

**Comment by flycat52** [comment]
same error. it seems the npm version does not get updated.

**Comment by dougludlow** [comment]
Hey all, I just published v0.8.0. Give that a try and lemme know what happens.

**Comment by curlyfro** [comment]
cool -- i'm going to test in a few hours.

**Comment by RodEsV** [comment]
Fast question,
How can i get the last version ? 
When I type npm install ---save ng2-bs3-modal I get the version with rc4

**Comment by dougludlow** [comment]
Hmm... that should do it, depending on your npm version I guess. Try updating your package.json manually to `^0.8.0`.

**Comment by RodEsV** [comment]
For the record 
npm version 3.10.3
and that works!

**Comment by dougludlow** [comment]
@curlyfro success?

**Comment by curlyfro** [comment]
sorry -- i haven't check yet.  checking now.  give me 30mins.

**Comment by curlyfro** [comment]
cool -- it works!

**Comment by dougludlow** [comment]
@curlyfro, awesome. Thanks for the followup.
